import {randomUUID} from 'node:crypto';import {admin,assertWorkspaceAccess} from './mcp-oauth';import {appOrigin,ConfigurationError,logFailure} from './config';
const BASE='https://apihub.agnes-ai.com';
const ratios=['9:16','16:9','1:1','4:3','3:4','21:9'] as const;
export type AiConcept={title:string;hook:string;script:string;caption:string;hashtags:string[];videoPrompt:string;aspectRatio:typeof ratios[number];seconds:number;platform:string;cta:string};
function key(){const value=process.env.AGNES_API_KEY;if(!value)throw new ConfigurationError('AGNES_API_KEY');return value}
async function agnes(path:string,init:RequestInit){const r=await fetch(BASE+path,{...init,headers:{Authorization:`Bearer ${key()}`,'Content-Type':'application/json',...(init.headers||{})},signal:AbortSignal.timeout(45000),redirect:'error'});const body=await r.json().catch(()=>null);if(!r.ok)throw new Error(`Agnes request failed (HTTP ${r.status})`);return body}
function jsonObject(raw:string){const cleaned=raw.trim().replace(/^\`\`\`(?:json)?\s*/i,'').replace(/\s*\`\`\`$/,'');const value=JSON.parse(cleaned);if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('AI returned an invalid content plan.');return value as Record<string,unknown>}
export async function createAiConcept(brief:string,platform:string,actorId:string,workspaceId:string){await assertWorkspaceAccess(actorId,workspaceId,true);const clean=brief.trim();if(clean.length<8||clean.length>3000)throw new Error('Describe the content you want in 8 to 3,000 characters.');const allowed=['tiktok','youtube','instagram','facebook','linkedin','x','general'];const target=allowed.includes(platform)?platform:'general';
 const system=`You are ChannelDesk's senior social content strategist. Turn a user's plain-English brief into a production-ready short-form social video plan. Return ONLY valid JSON with exactly these keys: title, hook, script, caption, hashtags, videoPrompt, aspectRatio, seconds, platform, cta. hashtags must be an array without #. seconds must be an integer 4-12. aspectRatio must be one of 9:16,16:9,1:1,4:3,3:4,21:9. Default TikTok/Instagram to 9:16 and YouTube Shorts to 9:16. Make videoPrompt visually explicit: subject, action, setting, camera, lighting, pacing and on-screen-safe composition. Never invent factual claims about the user's business, customers, results, prices or accreditations. Do not include copyrighted characters, celebrity likenesses, or unsafe content unless explicitly supplied and lawful.`;
 const out=await agnes('/v1/chat/completions',{method:'POST',body:JSON.stringify({model:'agnes-3.0-flash',messages:[{role:'system',content:system},{role:'user',content:`Target platform: ${target}\nBrief: ${clean}`}],temperature:.55,max_tokens:1800})});const raw=out?.choices?.[0]?.message?.content;if(typeof raw!=='string'||!raw.trim())throw new Error('Agnes did not return a content plan.');const v=jsonObject(raw);const ratio=ratios.includes(v.aspectRatio as any)?v.aspectRatio as AiConcept['aspectRatio']:(target==='tiktok'||target==='instagram'?'9:16':'16:9');const seconds=Math.max(4,Math.min(12,Math.round(Number(v.seconds)||8)));const text=(x:unknown,max:number)=>String(x||'').trim().slice(0,max);const hashtags=Array.isArray(v.hashtags)?v.hashtags.map(x=>text(x,60).replace(/^#/,'')).filter(Boolean).slice(0,15):[];
 const concept:AiConcept={title:text(v.title,120),hook:text(v.hook,300),script:text(v.script,3000),caption:text(v.caption,2200),hashtags,videoPrompt:text(v.videoPrompt,4000),aspectRatio:ratio,seconds,platform:target,cta:text(v.cta,300)};if(!concept.videoPrompt||!concept.caption)throw new Error('AI plan was incomplete. Try a more specific brief.');return concept}
export async function startAiVideo(concept:AiConcept,actorId:string,workspaceId:string,quality:'flash'|'quality'='flash'){await assertWorkspaceAccess(actorId,workspaceId,true);const model=quality==='quality'?'agnes-video-2.5':'agnes-video-2.5-flash',size=quality==='quality'?'1080P':'720P';const db=admin();const id=randomUUID();const {error:insertError}=await db.from('ai_generation_jobs').insert({id,workspace_id:workspaceId,created_by:actorId,kind:'video',provider:'agnes',model,status:'queued',prompt:concept.videoPrompt,brief:concept});if(insertError)throw insertError;
 try{const out=await agnes('/v1/videos',{method:'POST',body:JSON.stringify({model,prompt:concept.videoPrompt,mode:'text',seconds:String(concept.seconds),size,aspect_ratio:concept.aspectRatio,n:1})});const providerId=String(out?.video_id||out?.id||out?.data?.video_id||'');if(!providerId)throw new Error('Agnes accepted no video job ID.');const {error}=await db.from('ai_generation_jobs').update({provider_job_id:providerId,status:'generating',updated_at:new Date().toISOString()}).eq('id',id).eq('workspace_id',workspaceId);if(error)throw error;return {id,status:'generating' as const}}
 catch(e){const message=e instanceof Error?e.message:'Video generation could not start.';await db.from('ai_generation_jobs').update({status:'failed',error_message:message,updated_at:new Date().toISOString()}).eq('id',id);throw e}}
function completedUrl(body:any){const candidates=[body?.metadata?.url,body?.url,body?.data?.url,body?.video_url,body?.data?.video_url];return candidates.find(x=>typeof x==='string'&&/^https:\/\//.test(x)) as string|undefined}
export async function syncAiVideo(jobId:string,actorId:string,workspaceId:string){await assertWorkspaceAccess(actorId,workspaceId,true);const db=admin();const {data:job,error}=await db.from('ai_generation_jobs').select('*').eq('id',jobId).eq('workspace_id',workspaceId).maybeSingle();if(error||!job)throw new Error('AI generation job not found.');if(job.status==='completed'||job.status==='failed')return job;if(!job.provider_job_id)throw new Error('AI generation job has no provider reference.');
 try{const body=await agnes('/agnesapi?video_id='+encodeURIComponent(job.provider_job_id)+'&model_name='+encodeURIComponent(job.model),{method:'GET'});const url=completedUrl(body);const rawStatus=String(body?.status||body?.state||body?.metadata?.status||'').toLowerCase();if(!url){if(['failed','error','cancelled'].includes(rawStatus)){const message='Agnes video generation failed.';await db.from('ai_generation_jobs').update({status:'failed',error_message:message,result:body||{},updated_at:new Date().toISOString()}).eq('id',job.id);return {...job,status:'failed',error_message:message}}return {...job,status:'generating',result:{progress:body?.progress??body?.metadata?.progress??null}}}
  const response=await fetch(url,{signal:AbortSignal.timeout(120000),redirect:'follow'});if(!response.ok)throw new Error('Generated video could not be downloaded.');const length=Number(response.headers.get('content-length')||0);if(length>256*1024*1024)throw new Error('Generated video exceeds the 256 MB media limit.');const bytes=await response.arrayBuffer();if(bytes.byteLength>256*1024*1024)throw new Error('Generated video exceeds the 256 MB media limit.');const assetId=randomUUID(),storageKey=`${workspaceId}/${assetId}/agnes-${job.id}.mp4`;const {error:uploadError}=await db.storage.from('channeldesk-media').upload(storageKey,bytes,{contentType:'video/mp4',upsert:false,cacheControl:'3600'});if(uploadError)throw uploadError;const sourceUrl=appOrigin()+'/media/'+assetId;const {error:assetError}=await db.from('media_assets').insert({id:assetId,workspace_id:workspaceId,storage_key:storageKey,mime_type:'video/mp4',source_url:sourceUrl,rights_basis:'ai_generated',rights_evidence:`Agnes ${job.model}; job ${job.provider_job_id}`});if(assetError){await db.storage.from('channeldesk-media').remove([storageKey]);throw assetError}const result={provider:body,caption:job.brief?.caption,hashtags:job.brief?.hashtags};const {data:done,error:doneError}=await db.from('ai_generation_jobs').update({status:'completed',media_asset_id:assetId,result,error_message:null,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',job.id).eq('workspace_id',workspaceId).select('*').single();if(doneError)throw doneError;await db.from('audit_events').insert({workspace_id:workspaceId,actor_id:actorId,action:'ai.video_generated',entity_type:'media_asset',entity_id:assetId,metadata:{provider:'agnes',model:job.model,job_id:job.id}});return done}
 catch(e){logFailure('agnes.video.sync_failed',e);throw e}}
