import {admin} from '@/lib/mcp-oauth';
type Event={type:'publication_published'|'publication_failed'|'inbox_received'|'schedule'|'manual';workspaceId:string;actorId?:string|null;publicationId?:string;threadId?:string;payload?:Record<string,unknown>};

async function executeFlow(flow:any,event:Event){
 const db=admin();let actorId=event.actorId||null;if(!actorId){const {data:member}=await db.from('workspace_members').select('user_id').eq('workspace_id',event.workspaceId).in('role',['owner','admin','editor']).limit(1).maybeSingle();actorId=member?.user_id||null;}const {data:run,error:re}=await db.from('automation_flow_runs').insert({workspace_id:event.workspaceId,flow_id:flow.id,status:'running',trigger_event:event}).select('id').single();if(re)throw re;
 try{const results=[];for(const action of Array.isArray(flow.actions)?flow.actions:[]){const cfg=action.config||{};
  if(action.type==='create_draft'){const {data:connection}=await db.from('social_connections').select('id').eq('workspace_id',event.workspaceId).eq('active',true).limit(1).maybeSingle();if(connection){const {data:p,error:e}=await db.from('publications').insert({workspace_id:event.workspaceId,author_id:actorId,text:String(cfg.text||'Automated draft'),state:'draft'}).select('id').single();if(e)throw e;await db.from('publication_targets').insert({publication_id:p.id,connection_id:connection.id,state:'draft',network_payload:{source:'flow'},idempotency_key:`flow:${run.id}:${action.type}`});results.push({type:action.type,publicationId:p.id});}}
  else if(action.type==='add_inbox_note'&&event.threadId){const {error:e}=await db.from('inbox_messages').insert({thread_id:event.threadId,direction:'outbound',body:String(cfg.note||'Flow note'),author_name:'ChannelDesk Flow',sent_at:new Date().toISOString(),metadata:{internal_note:true,flow_id:flow.id}});if(e)throw e;results.push({type:action.type});}
  else if(action.type==='notify_workspace'){await db.from('audit_events').insert({workspace_id:event.workspaceId,actor_id:actorId,action:'flow.notification',entity_type:'automation_flow',entity_id:flow.id,metadata:{message:String(cfg.message||'Flow triggered'),event:event.type}});results.push({type:action.type});}
 }
 await db.from('automation_flow_runs').update({status:'completed',result:results,finished_at:new Date().toISOString()}).eq('id',run.id);await db.from('automation_flows').update({last_run_at:new Date().toISOString(),run_count:(Number(flow.run_count)||0)+1}).eq('id',flow.id);return {flowId:flow.id,runId:run.id,status:'completed',results};
 }catch(e){const msg=e instanceof Error?e.message:'Flow failed';await db.from('automation_flow_runs').update({status:'failed',error_message:msg,finished_at:new Date().toISOString()}).eq('id',run.id);await db.from('automation_flows').update({last_run_at:new Date().toISOString(),run_count:(Number(flow.run_count)||0)+1,error_count:(Number(flow.error_count)||0)+1}).eq('id',flow.id);return {flowId:flow.id,runId:run.id,status:'failed',error:msg};}
}
export async function runFlows(event:Event){const db=admin();const {data:flows,error}=await db.from('automation_flows').select('*').eq('workspace_id',event.workspaceId).eq('trigger_type',event.type).eq('active',true);if(error)throw error;const out=[];for(const flow of flows||[]){if(event.type==='schedule'){const cadence=String(flow.trigger_config?.cadence||'daily'),last=flow.last_run_at?Date.parse(flow.last_run_at):0,wait=cadence==='weekly'?7*86400000:86400000;if(last&&Date.now()-last<wait)continue;}out.push(await executeFlow(flow,event));}return out;}
export async function runFlowById(flowId:string,workspaceId:string,actorId:string,payload:Record<string,unknown>={}){const {data:flow,error}=await admin().from('automation_flows').select('*').eq('id',flowId).eq('workspace_id',workspaceId).maybeSingle();if(error)throw error;if(!flow)throw new Error('Flow not found in this workspace.');return executeFlow(flow,{type:'manual',workspaceId,actorId,payload});}
