import {createMcpHandler,McpServer} from '@modelcontextprotocol/server';
import * as z from 'zod/v4';
import {cancelYouTubeSchedule,createYouTubePublication,getCalendar,getPublicationStatus,listSocialAccounts,rescheduleYouTubePublication,syncYouTubePublication,getTikTokCreatorInfo,publishTikTok,uploadTikTokDraft,getTikTokPostStatus,syncYouTubeAnalytics} from './publishing';
import {admin,assertWorkspaceAccess} from './mcp-oauth';
import {logFailure} from './config';
const result=(value:unknown)=>({content:[{type:'text' as const,text:JSON.stringify(value,null,2)}],structuredContent:{result:value}});
function failure(error:unknown){
 logFailure('mcp.tool.failed',error);
 const message=error instanceof Error&&error.message?error.message:'ChannelDesk could not complete the operation.';
 return {content:[{type:'text' as const,text:message}],structuredContent:{error:{message}},isError:true};
}
function metadata(write=false){const scopes=write?['channeldesk.read','channeldesk.publish']:['channeldesk.read'];return {_meta:{securitySchemes:[{type:'oauth2',scopes}]},annotations:{readOnlyHint:!write,destructiveHint:write,idempotentHint:!write,openWorldHint:true}};}
export function buildMcp(userId:string,scopes:string[]){
 const server=new McpServer({name:'ChannelDesk',version:'0.5.0'},{capabilities:{tools:{}}});
 const guard=async(workspaceId:string,write=false)=>{const scope=write?'channeldesk.publish':'channeldesk.read';if(!scopes.includes(scope))throw new Error(`Reconnect ChannelDesk with ${scope} access.`);await assertWorkspaceAccess(userId,workspaceId,write);};
 const workspace={workspaceId:z.string().uuid()};const publication={...workspace,publicationId:z.string().uuid()};
 server.registerTool('list_workspaces',{description:'List your accessible ChannelDesk workspaces and roles. Use returned IDs for subsequent tools.',...metadata(),inputSchema:z.object({})},async()=>{try{if(!scopes.includes('channeldesk.read'))throw new Error('Read access is required.');const {data,error}=await admin().from('workspace_members').select('workspace_id,role,workspaces(name,slug)').eq('user_id',userId);if(error)throw error;return result(data||[]);}catch(e){return failure(e);}});
 server.registerTool('list_social_accounts',{description:'List actual active accounts in a workspace. Use a returned connection ID when publishing.',...metadata(),inputSchema:z.object(workspace)},async({workspaceId})=>{try{await guard(workspaceId);return result(await listSocialAccounts(workspaceId));}catch(e){return failure(e);}});
 server.registerTool('get_calendar',{description:'Get up to 200 scheduled publications in an ISO date range.',...metadata(),inputSchema:z.object({...workspace,from:z.string().datetime({offset:true}),to:z.string().datetime({offset:true})})},async({workspaceId,from,to})=>{try{await guard(workspaceId);return result(await getCalendar(from,to,workspaceId));}catch(e){return failure(e);}});
 const content={...workspace,connectionId:z.string().uuid(),title:z.string().min(1).max(100),description:z.string().max(5000).optional(),mediaUrl:z.string().url(),madeForKids:z.boolean(),tags:z.array(z.string().max(100)).max(30).optional(),requestId:z.string().min(8).max(128)};
 server.registerTool('publish_youtube',{description:'Upload to the exact selected YouTube account. Requires user authorisation for the content, account, visibility and kids setting. Use a stable requestId on retries. Files must be public HTTPS videos up to 256 MB. Never retry needs_review by inventing a new requestId.',...metadata(true),inputSchema:z.object({...content,privacy:z.enum(['private','unlisted','public'])})},async({workspaceId,...args})=>{try{await guard(workspaceId,true);return result(await createYouTubePublication(args,workspaceId,userId));}catch(e){return failure(e);}});
 server.registerTool('schedule_youtube',{description:'Upload an authorised video as private, then let YouTube publish it at a future time. Requires an explicit account and a stable requestId. Platform approval may restrict public publishing.',...metadata(true),inputSchema:z.object({...content,scheduledFor:z.string().datetime({offset:true})})},async({workspaceId,...args})=>{try{await guard(workspaceId,true);return result(await createYouTubePublication({...args,privacy:'private'},workspaceId,userId));}catch(e){return failure(e);}});
 server.registerTool('get_publication_status',{description:'Read saved per-network publication status. A needs_review state requires checking the existing video; do not re-upload.',...metadata(),inputSchema:z.object(publication)},async({workspaceId,publicationId})=>{try{await guard(workspaceId);return result(await getPublicationStatus(publicationId,workspaceId));}catch(e){return failure(e);}});
 server.registerTool('sync_youtube_status',{description:'Read YouTube processing and privacy status and update the saved publication.',...metadata(true),inputSchema:z.object(publication)},async({workspaceId,publicationId})=>{try{await guard(workspaceId,true);return result(await syncYouTubePublication(publicationId,workspaceId,userId));}catch(e){return failure(e);}});
 server.registerTool('reschedule_youtube',{description:'Move an authorised, still-private scheduled video to another future time. Requires the YouTube management permission; old connections may need reconnecting.',...metadata(true),inputSchema:z.object({...publication,scheduledFor:z.string().datetime({offset:true})})},async({workspaceId,publicationId,scheduledFor})=>{try{await guard(workspaceId,true);return result(await rescheduleYouTubePublication(publicationId,scheduledFor,workspaceId,userId));}catch(e){return failure(e);}});
 server.registerTool('get_tiktok_creator_info',{description:'Read the selected TikTok creator capabilities before Direct Post. Use the returned privacy options and disabled interaction settings when asking the user to authorise a post.',...metadata(),inputSchema:z.object({...workspace,connectionId:z.string().uuid()})},async({workspaceId,connectionId})=>{try{await guard(workspaceId);return result(await getTikTokCreatorInfo(connectionId,workspaceId,userId));}catch(e){return failure(e);}});
 server.registerTool('publish_tiktok',{description:'Direct-post an authorised video to the exact selected TikTok account. Query creator info first and honour the creator privacy/interaction options. TikTok may restrict unaudited clients to private visibility. Media URL must be public HTTPS and from a URL/domain TikTok accepts for PULL_FROM_URL.',...metadata(true),inputSchema:z.object({...workspace,connectionId:z.string().uuid(),caption:z.string().max(2200),mediaUrl:z.string().url(),privacy:z.enum(['PUBLIC_TO_EVERYONE','MUTUAL_FOLLOW_FRIENDS','FOLLOWER_OF_CREATOR','SELF_ONLY']),disableComment:z.boolean(),disableDuet:z.boolean(),disableStitch:z.boolean(),requestId:z.string().min(8).max(128)})},async({workspaceId,...args})=>{try{await guard(workspaceId,true);return result(await publishTikTok(args,workspaceId,userId));}catch(e){return failure(e);}});
 server.registerTool('upload_tiktok_draft',{description:'Upload an authorised video to the selected TikTok account inbox for the user to finish editing/posting in TikTok. Requires video.upload permission.',...metadata(true),inputSchema:z.object({...workspace,connectionId:z.string().uuid(),mediaUrl:z.string().url(),requestId:z.string().min(8).max(128)})},async({workspaceId,...args})=>{try{await guard(workspaceId,true);return result(await uploadTikTokDraft(args,workspaceId,userId));}catch(e){return failure(e);}});
 server.registerTool('get_tiktok_post_status',{description:'Check TikTok Content Posting API processing status for a publish ID.',...metadata(),inputSchema:z.object({...workspace,connectionId:z.string().uuid(),publishId:z.string().min(1).max(256)})},async({workspaceId,connectionId,publishId})=>{try{await guard(workspaceId);return result(await getTikTokPostStatus(connectionId,publishId,workspaceId,userId));}catch(e){return failure(e);}});
 server.registerTool('list_media',{description:'List reusable media in a ChannelDesk workspace so content can be created from uploaded assets without asking for raw URLs.',...metadata(),inputSchema:z.object({...workspace,type:z.enum(['video','image','all']).default('all')})},async({workspaceId,type})=>{try{await guard(workspaceId);let q=admin().from('media_assets').select('id,storage_key,mime_type,width,height,duration_ms,source_url,rights_basis,created_at').eq('workspace_id',workspaceId).order('created_at',{ascending:false}).limit(100);if(type!=='all')q=q.like('mime_type',type+'/%');const {data,error}=await q;if(error)throw error;return result(data||[]);}catch(e){return failure(e);}});
 server.registerTool('sync_youtube_analytics',{description:'Fetch real YouTube Analytics for the selected connected channel and save daily metrics in ChannelDesk. Reconnect older YouTube connections if analytics permission is missing.',...metadata(true),inputSchema:z.object({...workspace,connectionId:z.string().uuid(),days:z.number().int().min(1).max(90).default(30)})},async({workspaceId,connectionId,days})=>{try{await guard(workspaceId,true);return result(await syncYouTubeAnalytics(connectionId,workspaceId,userId,days));}catch(e){return failure(e);}});
 server.registerTool('get_analytics_summary',{description:'Get trustworthy ChannelDesk publishing and saved network analytics for a date range. Metrics are returned only when actually stored; nothing is estimated.',...metadata(),inputSchema:z.object({...workspace,from:z.string().datetime({offset:true}),to:z.string().datetime({offset:true})})},async({workspaceId,from,to})=>{try{await guard(workspaceId);const db=admin();const [{data:pubs,error:pe},{data:snapshots,error:ae}]=await Promise.all([db.from('publications').select('id,state,created_at').eq('workspace_id',workspaceId).gte('created_at',from).lte('created_at',to),db.from('analytics_snapshots').select('metric_date,metrics,connection_id,external_post_id').eq('workspace_id',workspaceId).gte('metric_date',from.slice(0,10)).lte('metric_date',to.slice(0,10)).order('metric_date',{ascending:true})]);if(pe)throw pe;if(ae)throw ae;const rows=pubs||[];return result({created:rows.length,published:rows.filter(x=>x.state==='published').length,scheduled:rows.filter(x=>x.state==='scheduled').length,failed:rows.filter(x=>['failed','needs_review'].includes(x.state)).length,networkMetrics:snapshots||[]});}catch(e){return failure(e);}});
 server.registerTool('list_inbox',{description:'List open social conversations saved in the unified ChannelDesk Inbox.',...metadata(),inputSchema:z.object({...workspace,status:z.enum(['open','closed','all']).default('open'),limit:z.number().int().min(1).max(100).default(50)})},async({workspaceId,status,limit})=>{try{await guard(workspaceId);let q=admin().from('inbox_threads').select('id,kind,participant_name,status,last_message_at,assigned_to,connection_id').eq('workspace_id',workspaceId).order('last_message_at',{ascending:false}).limit(limit);if(status!=='all')q=q.eq('status',status);const {data,error}=await q;if(error)throw error;return result(data||[]);}catch(e){return failure(e);}});
 server.registerTool('list_competitors',{description:'List competitor profiles configured for benchmarking in a ChannelDesk workspace.',...metadata(),inputSchema:z.object(workspace)},async({workspaceId})=>{try{await guard(workspaceId);const {data,error}=await admin().from('competitors').select('id,network,handle,display_name,active,created_at').eq('workspace_id',workspaceId).eq('active',true).order('created_at',{ascending:false});if(error)throw error;return result(data||[]);}catch(e){return failure(e);}});
 server.registerTool('list_smart_links',{description:'List ChannelDesk link-in-bio pages and their saved destinations/click counts.',...metadata(),inputSchema:z.object(workspace)},async({workspaceId})=>{try{await guard(workspaceId);const {data,error}=await admin().from('smart_links').select('id,slug,title,description,active,smart_link_items(id,label,url,position,active,clicks)').eq('workspace_id',workspaceId).order('created_at',{ascending:false});if(error)throw error;return result(data||[]);}catch(e){return failure(e);}});
 server.registerTool('list_automations',{description:'List configured ChannelDesk automation flows and whether each is active.',...metadata(),inputSchema:z.object(workspace)},async({workspaceId})=>{try{await guard(workspaceId);const {data,error}=await admin().from('automation_flows').select('id,name,trigger_type,trigger_config,actions,active,created_at,updated_at').eq('workspace_id',workspaceId).order('created_at',{ascending:false});if(error)throw error;return result(data||[]);}catch(e){return failure(e);}});
 server.registerTool('cancel_youtube_schedule',{description:'Cancel the user-selected future schedule, keeping the already uploaded video private. Will not hide an already public video.',...metadata(true),inputSchema:z.object(publication)},async({workspaceId,publicationId})=>{try{await guard(workspaceId,true);return result(await cancelYouTubeSchedule(publicationId,workspaceId,userId));}catch(e){return failure(e);}});
 return createMcpHandler(()=>server);
}
