import {createMcpHandler,McpServer} from '@modelcontextprotocol/server';
import * as z from 'zod/v4';
import {cancelYouTubeSchedule,createYouTubePublication,getCalendar,getPublicationStatus,listSocialAccounts,rescheduleYouTubePublication,syncYouTubePublication} from './publishing';
import {admin,assertWorkspaceAccess} from './mcp-oauth';
import {logFailure} from './config';
const result=(value:unknown)=>({content:[{type:'text' as const,text:JSON.stringify(value,null,2)}],structuredContent:{result:value}});
function failure(error:unknown){
 logFailure('mcp.tool.failed',error);
 const message=error instanceof Error&&error.message?error.message:'ChannelDesk could not complete the operation.';
 return {content:[{type:'text' as const,text:message}],structuredContent:{error:{message}},isError:true};
}
function metadata(write=false){const scopes=write?['channeldesk.read','channeldesk.publish']:['channeldesk.read'];return {_meta:{securitySchemes:[{type:'oauth2',scopes}]},annotations:{readOnlyHint:!write,destructiveHint:write,idempotentHint:!write,openWorldHint:true}};}
export function buildMcp(userId:string,scopes:string[]){
 const server=new McpServer({name:'ChannelDesk',version:'0.3.0'},{capabilities:{tools:{}}});
 const guard=async(workspaceId:string,write=false)=>{const scope=write?'channeldesk.publish':'channeldesk.read';if(!scopes.includes(scope))throw new Error(`Reconnect ChannelDesk with ${scope} access.`);await assertWorkspaceAccess(userId,workspaceId,write);};
 const workspace={workspaceId:z.string().uuid()};const publication={...workspace,publicationId:z.string().uuid()};
 server.registerTool('list_workspaces',{description:'List your accessible ChannelDesk workspaces and roles. Use returned IDs for subsequent tools.',...metadata(),inputSchema:z.object({})},async()=>{try{if(!scopes.includes('channeldesk.read'))throw new Error('Read access is required.');const {data,error}=await admin().from('workspace_members').select('workspace_id,role,workspaces(name,slug)').eq('user_id',userId);if(error)throw error;return result(data||[]);}catch(e){return failure(e);}});
 server.registerTool('list_social_accounts',{description:'List actual active accounts in a workspace. Use a returned connection ID when publishing.',...metadata(),inputSchema:z.object(workspace)},async({workspaceId})=>{try{await guard(workspaceId);return result(await listSocialAccounts(workspaceId));}catch(e){return failure(e);}});
 server.registerTool('get_calendar',{description:'Get up to 200 scheduled publications in an ISO date range.',...metadata(),inputSchema:z.object({...workspace,from:z.string().datetime({offset:true}),to:z.string().datetime({offset:true})})},async({workspaceId,from,to})=>{try{await guard(workspaceId);return result(await getCalendar(from,to,workspaceId));}catch(e){return failure(e);}});
 const content={...workspace,connectionId:z.string().uuid(),title:z.string().min(1).max(100),description:z.string().max(5000).optional(),mediaUrl:z.string().url(),madeForKids:z.boolean(),tags:z.array(z.string().max(100)).max(30).optional(),requestId:z.string().min(8).max(128)};
 server.registerTool('publish_youtube',{description:'Upload to the exact selected YouTube account. Requires user authorisation for the content, account, visibility and kids setting. Use a stable requestId on retries. Files must be public HTTPS videos up to 256 MB. Never retry needs_review by inventing a new requestId.',...metadata(true),inputSchema:z.object({...content,privacy:z.enum(['private','unlisted','public'])})},async({workspaceId,...args})=>{try{await guard(workspaceId,true);return result(await createYouTubePublication(args,workspaceId,userId));}catch(e){return failure(e);}});
 server.registerTool('schedule_youtube',{description:'Upload an authorised video as private, then let YouTube publish it at a future time. Requires an explicit account and a stable requestId. Platform approval may restrict public publishing.',...metadata(true),inputSchema:z.object({...content,scheduledFor:z.string().datetime({offset:true})})},async({workspaceId,...args})=>{try{await guard(workspaceId,true);return result(await createYouTubePublication({...args,privacy:'private'},workspaceId,userId));}catch(e){return failure(e);}});
 server.registerTool('get_publication_status',{description:'Read saved per-network publication status. A needs_review state requires checking the existing video; do not re-upload.',...metadata(),inputSchema:z.object(publication)},async({workspaceId,publicationId})=>{try{await guard(workspaceId);return result(await getPublicationStatus(publicationId,workspaceId));}catch(e){return failure(e);}});
 server.registerTool('sync_youtube_status',{description:'Read YouTube processing and privacy status and update the saved publication.',...metadata(true),inputSchema:z.object(publication)},async({workspaceId,publicationId})=>{try{await guard(workspaceId,true);return result(await syncYouTubePublication(publicationId,workspaceId,userId));}catch(e){return failure(e);}});
 server.registerTool('reschedule_youtube',{description:'Move an authorised, still-private scheduled video to another future time. Requires the YouTube management permission; old connections may need reconnecting.',...metadata(true),inputSchema:z.object({...publication,scheduledFor:z.string().datetime({offset:true})})},async({workspaceId,publicationId,scheduledFor})=>{try{await guard(workspaceId,true);return result(await rescheduleYouTubePublication(publicationId,scheduledFor,workspaceId,userId));}catch(e){return failure(e);}});
 server.registerTool('cancel_youtube_schedule',{description:'Cancel the user-selected future schedule, keeping the already uploaded video private. Will not hide an already public video.',...metadata(true),inputSchema:z.object(publication)},async({workspaceId,publicationId})=>{try{await guard(workspaceId,true);return result(await cancelYouTubeSchedule(publicationId,workspaceId,userId));}catch(e){return failure(e);}});
 return createMcpHandler(()=>server);
}
