import {createDecipheriv,createCipheriv,randomBytes} from 'node:crypto';
import {z} from 'zod';
import {admin,assertWorkspaceAccess,hashSecret} from './mcp-oauth';
import {fetchVideo,validateMediaUrl} from './media-fetch';
import {ConfigurationError,logFailure} from './config';
function key(){const k=Buffer.from(process.env.TOKEN_ENCRYPTION_KEY||'','base64');if(k.length!==32)throw new ConfigurationError('TOKEN_ENCRYPTION_KEY');return k;}
export function decrypt(value:string){const [iv,tag,data]=value.split('.');if(!iv||!tag||!data)throw new Error('Stored channel credentials are invalid. Reconnect YouTube.');const d=createDecipheriv('aes-256-gcm',key(),Buffer.from(iv,'base64'));d.setAuthTag(Buffer.from(tag,'base64'));return Buffer.concat([d.update(Buffer.from(data,'base64')),d.final()]).toString('utf8');}
export function encrypt(value:string){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',key(),iv);const data=Buffer.concat([c.update(value,'utf8'),c.final()]);return [iv.toString('base64'),c.getAuthTag().toString('base64'),data.toString('base64')].join('.');}
type Connection={id:string;workspace_id:string;external_account_id:string;display_name:string;token_ciphertext:string;refresh_token_ciphertext:string|null;token_expires_at:string|null;scopes:string[]};
type VideoStatus={uploadStatus?:string;privacyStatus?:string;publishAt?:string;failureReason?:string;rejectionReason?:string;selfDeclaredMadeForKids?:boolean;embeddable?:boolean;publicStatsViewable?:boolean;license?:string};
export const publicationInput=z.object({connectionId:z.string().uuid(),title:z.string().trim().min(1).max(100),description:z.string().max(5000).default(''),mediaUrl:z.string().url(),scheduledFor:z.string().datetime({offset:true}).optional(),privacy:z.enum(['private','unlisted','public']),madeForKids:z.boolean(),tags:z.array(z.string().max(100)).max(30).default([]),requestId:z.string().min(8).max(128)}).strict();
export type PublicationInput=z.input<typeof publicationInput>;
async function youtubeAccessToken(c:Connection){
 if(c.token_expires_at&&Date.parse(c.token_expires_at)>Date.now()+60000)return decrypt(c.token_ciphertext);
 if(!c.refresh_token_ciphertext)throw new Error('Reconnect YouTube to renew channel access.');
 if(!process.env.GOOGLE_OAUTH_CLIENT_ID||!process.env.GOOGLE_OAUTH_CLIENT_SECRET)throw new ConfigurationError('Google OAuth credentials');
 const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:process.env.GOOGLE_OAUTH_CLIENT_ID,client_secret:process.env.GOOGLE_OAUTH_CLIENT_SECRET,refresh_token:decrypt(c.refresh_token_ciphertext),grant_type:'refresh_token'}),signal:AbortSignal.timeout(20000),redirect:'error'});
 if(!r.ok)throw new Error('Google could not renew channel access. Reconnect YouTube.');const t=await r.json();if(!t.access_token||!Number.isFinite(t.expires_in))throw new Error('Google returned invalid channel credentials.');
 const {error}=await admin().from('social_connections').update({token_ciphertext:encrypt(t.access_token),token_expires_at:new Date(Date.now()+t.expires_in*1000).toISOString(),...(t.refresh_token?{refresh_token_ciphertext:encrypt(t.refresh_token)}:{})}).eq('id',c.id).eq('workspace_id',c.workspace_id);if(error)throw error;return t.access_token as string;
}
export async function syncYouTubeComments(connectionId:string,workspaceId:string,actorId:string,maxResults=100){
 await assertWorkspaceAccess(actorId,workspaceId,true);const db=admin();const {data:c,error}=await db.from('social_connections').select('*').eq('id',connectionId).eq('workspace_id',workspaceId).eq('network','youtube').eq('active',true).maybeSingle();if(error||!c)throw new Error('Choose an active YouTube account in this workspace.');if(!Array.isArray(c.scopes)||!c.scopes.includes('https://www.googleapis.com/auth/youtube.force-ssl'))throw new Error('Reconnect YouTube to grant comment management permission.');const access=await youtubeAccessToken(c as Connection);
 let pageToken:string|undefined,imported=0,pages=0;do{const u=new URL('https://www.googleapis.com/youtube/v3/commentThreads');u.searchParams.set('part','snippet,replies');u.searchParams.set('allThreadsRelatedToChannelId',c.external_account_id);u.searchParams.set('maxResults',String(Math.min(100,maxResults-imported)));u.searchParams.set('order','time');u.searchParams.set('textFormat','plainText');if(pageToken)u.searchParams.set('pageToken',pageToken);const r=await fetch(u,{headers:{Authorization:`Bearer ${access}`},signal:AbortSignal.timeout(30000),redirect:'error'});const body=await r.json().catch(()=>null);if(!r.ok)throw new Error(`YouTube comment sync failed (HTTP ${r.status})${body?.error?.message?`: ${body.error.message}`:''}.`);
 for(const item of body?.items||[]){const top=item.snippet?.topLevelComment,videoId=item.snippet?.videoId,commentId=top?.id;if(!commentId)continue;const sn=top.snippet||{};const {data:thread,error:te}=await db.from('inbox_threads').upsert({workspace_id:workspaceId,connection_id:connectionId,external_thread_id:commentId,kind:'comment',participant_name:sn.authorDisplayName||'YouTube user',participant_avatar_url:sn.authorProfileImageUrl||null,status:'open',last_message_at:sn.publishedAt||new Date().toISOString()},{onConflict:'connection_id,external_thread_id'}).select('id').single();if(te)throw te;const messages:Array<{external_message_id:string;direction:'inbound'|'outbound';body:string;author_name:string;sent_at:string;metadata:Record<string,unknown>}>= [{external_message_id:commentId,direction:'inbound',body:sn.textDisplay||sn.textOriginal||'',author_name:sn.authorDisplayName||'YouTube user',sent_at:sn.publishedAt||new Date().toISOString(),metadata:{network:'youtube',videoId,likeCount:sn.likeCount||0,updatedAt:sn.updatedAt||null}}];for(const reply of item.replies?.comments||[]){const rs=reply.snippet||{};messages.push({external_message_id:reply.id,direction:rs.authorChannelId?.value===c.external_account_id?'outbound':'inbound',body:rs.textDisplay||rs.textOriginal||'',author_name:rs.authorDisplayName||'YouTube user',sent_at:rs.publishedAt||new Date().toISOString(),metadata:{network:'youtube',videoId,parentId:commentId,likeCount:rs.likeCount||0,updatedAt:rs.updatedAt||null}});}const {error:me}=await db.from('inbox_messages').upsert(messages.map(m=>({...m,thread_id:thread.id})),{onConflict:'thread_id,external_message_id'});if(me)throw me;imported++;}
 pageToken=body?.nextPageToken;pages++;}while(pageToken&&imported<maxResults&&pages<10);
 await db.from('audit_events').insert({workspace_id:workspaceId,actor_id:actorId,action:'youtube.comments_synced',entity_type:'social_connection',entity_id:connectionId,metadata:{imported}});return {connectionId,imported};
}
export async function replyToYouTubeComment(threadId:string,body:string,workspaceId:string,actorId:string){
 await assertWorkspaceAccess(actorId,workspaceId,true);const text=body.trim();if(!text||text.length>10000)throw new Error('Reply must be between 1 and 10,000 characters.');const db=admin();const {data:t,error}=await db.from('inbox_threads').select('id,external_thread_id,connection_id').eq('id',threadId).eq('workspace_id',workspaceId).eq('kind','comment').maybeSingle();if(error||!t)throw new Error('Choose a YouTube comment from this workspace.');const {data:c,error:ce}=await db.from('social_connections').select('*').eq('id',t.connection_id).eq('workspace_id',workspaceId).eq('network','youtube').eq('active',true).maybeSingle();if(ce||!c)throw new Error('The YouTube connection is unavailable.');const access=await youtubeAccessToken(c as Connection);const r=await fetch('https://www.googleapis.com/youtube/v3/comments?part=snippet',{method:'POST',headers:{Authorization:`Bearer ${access}`,'Content-Type':'application/json'},body:JSON.stringify({snippet:{parentId:t.external_thread_id,textOriginal:text}}),signal:AbortSignal.timeout(30000),redirect:'error'});const out=await r.json().catch(()=>null);if(!r.ok||!out?.id)throw new Error(`YouTube reply failed (HTTP ${r.status})${out?.error?.message?`: ${out.error.message}`:''}.`);const sn=out.snippet||{};const {error:me}=await db.from('inbox_messages').upsert({thread_id:t.id,external_message_id:out.id,direction:'outbound',body:text,author_name:sn.authorDisplayName||c.display_name,sent_at:sn.publishedAt||new Date().toISOString(),metadata:{network:'youtube',parentId:t.external_thread_id}},{onConflict:'thread_id,external_message_id'});if(me)throw me;await db.from('inbox_threads').update({last_message_at:sn.publishedAt||new Date().toISOString()}).eq('id',t.id).eq('workspace_id',workspaceId);await db.from('audit_events').insert({workspace_id:workspaceId,actor_id:actorId,action:'youtube.comment_replied',entity_type:'inbox_thread',entity_id:t.id,metadata:{commentId:out.id}});return {threadId:t.id,commentId:out.id,state:'sent'};
}
export async function syncYouTubeAnalytics(connectionId:string,workspaceId:string,actorId:string,days=30){
 await assertWorkspaceAccess(actorId,workspaceId,true);const db=admin();const {data:c,error}=await db.from('social_connections').select('*').eq('id',connectionId).eq('workspace_id',workspaceId).eq('network','youtube').eq('active',true).maybeSingle();if(error||!c)throw new Error('Choose an active YouTube account in this workspace.');if(!Array.isArray(c.scopes)||!c.scopes.includes('https://www.googleapis.com/auth/yt-analytics.readonly'))throw new Error('Reconnect YouTube to grant analytics permission.');
 const access=await youtubeAccessToken(c as Connection),end=new Date(),start=new Date(Date.now()-(Math.max(1,Math.min(days,90))-1)*86400000);const date=(d:Date)=>d.toISOString().slice(0,10);
 const u=new URL('https://youtubeanalytics.googleapis.com/v2/reports');u.searchParams.set('ids','channel==MINE');u.searchParams.set('startDate',date(start));u.searchParams.set('endDate',date(end));u.searchParams.set('metrics','views,estimatedMinutesWatched,averageViewDuration,likes,comments,shares,subscribersGained,subscribersLost');u.searchParams.set('dimensions','day');u.searchParams.set('sort','day');
 const r=await fetch(u,{headers:{Authorization:`Bearer ${access}`},signal:AbortSignal.timeout(30000),redirect:'error'});const body=await r.json().catch(()=>null);if(!r.ok)throw new Error(`YouTube Analytics sync failed (HTTP ${r.status})${body?.error?.message?`: ${body.error.message}`:''}.`);
 const headers=(body?.columnHeaders||[]).map((h:any)=>h.name);const rows=(body?.rows||[]) as unknown[][];const inserts=rows.map(row=>{const o=Object.fromEntries(headers.map((h:string,i:number)=>[h,row[i]]));return {workspace_id:workspaceId,connection_id:connectionId,metric_date:String(o.day),metrics:{views:Number(o.views||0),watch_minutes:Number(o.estimatedMinutesWatched||0),average_view_duration:Number(o.averageViewDuration||0),likes:Number(o.likes||0),comments:Number(o.comments||0),shares:Number(o.shares||0),subscribers_gained:Number(o.subscribersGained||0),subscribers_lost:Number(o.subscribersLost||0)}};});
 if(inserts.length){const dates=inserts.map(x=>x.metric_date);const {error:del}=await db.from('analytics_snapshots').delete().eq('workspace_id',workspaceId).eq('connection_id',connectionId).is('external_post_id',null).gte('metric_date',dates[0]).lte('metric_date',dates[dates.length-1]);if(del)throw del;const {error:ins}=await db.from('analytics_snapshots').insert(inserts);if(ins)throw ins;}
 const totals=inserts.reduce((a,x)=>{for(const [k,v] of Object.entries(x.metrics))a[k]=(a[k]||0)+Number(v);return a;},{} as Record<string,number>);await db.from('audit_events').insert({workspace_id:workspaceId,actor_id:actorId,action:'youtube.analytics_synced',entity_type:'social_connection',entity_id:connectionId,metadata:{days:inserts.length}});return {connectionId,from:date(start),to:date(end),days:inserts.length,totals};
}
export async function listSocialAccounts(workspaceId:string){const {data,error}=await admin().from('social_connections').select('id,network,external_account_id,display_name,active,token_expires_at').eq('workspace_id',workspaceId).eq('active',true);if(error)throw error;return data||[];}
export async function getCalendar(from:string,to:string,workspaceId:string){if(Date.parse(to)<Date.parse(from))throw new Error('Calendar end must follow its start.');const {data,error}=await admin().from('publications').select('id,text,state,scheduled_for,created_at,publication_targets(id,state,external_post_id,external_url,error_code,error_message,social_connections(network,display_name))').eq('workspace_id',workspaceId).gte('scheduled_for',from).lte('scheduled_for',to).order('scheduled_for').limit(200);if(error)throw error;return data||[];}
class UploadError extends Error {constructor(message:string,public uncertain=false){super(message);}}
export async function createYouTubePublication(raw:PublicationInput,workspaceId:string,actorId:string){
 const input=publicationInput.parse(raw);await assertWorkspaceAccess(actorId,workspaceId,true);const db=admin();const mediaUrl=validateMediaUrl(input.mediaUrl).href;
 const scheduled=input.scheduledFor?new Date(input.scheduledFor):null;if(scheduled&&scheduled.getTime()<=Date.now()+60000)throw new Error('Choose a schedule at least one minute in the future.');if(input.tags.join(',').length>500)throw new Error('YouTube tags must total 500 characters or fewer.');
 const {data:connection,error}=await db.from('social_connections').select('*').eq('id',input.connectionId).eq('workspace_id',workspaceId).eq('network','youtube').eq('active',true).single();if(error||!connection)throw new Error('Choose an active YouTube account in this workspace.');
 const payload={title:input.title,description:input.description,mediaUrl,tags:input.tags,madeForKids:input.madeForKids,privacy:scheduled?'private':input.privacy,scheduledFor:scheduled?.toISOString()||null};
 const {data:claim,error:claimError}=await db.rpc('claim_youtube_publication',{p_workspace_id:workspaceId,p_actor_id:actorId,p_connection_id:input.connectionId,p_payload:payload,p_request_id:input.requestId,p_request_hash:hashSecret(JSON.stringify({connectionId:input.connectionId,...payload}))});if(claimError)throw new Error(claimError.code==='22023'?claimError.message:'The publication could not be saved. Check the database migration.');if(claim.idempotentReplay)return claim;
 let videoId:string|null=null;
 try{
  const result=await uploadYouTube(connection,payload);videoId=result.id;
  const state=scheduled?'scheduled':result.status?.uploadStatus==='processed'&&result.status?.privacyStatus===payload.privacy?'published':'publishing';
  const {error:saveError}=await db.rpc('finish_youtube_publication',{p_publication_id:claim.publicationId,p_target_id:claim.targetId,p_state:state,p_video_id:videoId,p_error:null,p_actor_id:actorId});if(saveError)throw new UploadError('YouTube accepted the upload, but saving its status failed. Check YouTube before trying again.',true);
  return {...claim,videoId,url:`https://www.youtube.com/watch?v=${videoId}`,state,privacy:result.status?.privacyStatus,scheduledFor:scheduled?.toISOString()||null};
 }catch(e){
  const uncertain=videoId!==null||(e instanceof UploadError&&e.uncertain);const message=e instanceof Error?e.message:'YouTube upload failed.';const state=uncertain?'needs_review':'failed';
  const {error:saveError}=await db.rpc('finish_youtube_publication',{p_publication_id:claim.publicationId,p_target_id:claim.targetId,p_state:state,p_video_id:videoId,p_error:message,p_actor_id:actorId});if(saveError)logFailure('youtube.result_persist_failed',saveError);
  return {...claim,state,error:message,videoId,url:videoId?`https://www.youtube.com/watch?v=${videoId}`:null,needsReview:uncertain};
 }
}
async function uploadYouTube(connection:Connection,payload:any){
 const access=await youtubeAccessToken(connection);const media=await fetchVideo(payload.mediaUrl);
 try{
  const status={privacyStatus:payload.scheduledFor?'private':payload.privacy,selfDeclaredMadeForKids:payload.madeForKids,...(payload.scheduledFor?{publishAt:payload.scheduledFor}:{})};
  const init=await fetch('https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status',{method:'POST',headers:{Authorization:`Bearer ${access}`,'Content-Type':'application/json','X-Upload-Content-Length':String(media.size),'X-Upload-Content-Type':media.type},body:JSON.stringify({snippet:{title:payload.title,description:payload.description,tags:payload.tags},status}),signal:AbortSignal.timeout(20000),redirect:'error'});
  if(!init.ok)throw new UploadError(`YouTube rejected upload initialisation (HTTP ${init.status}).`);
  const location=init.headers.get('location');if(!location||new URL(location).origin!=='https://www.googleapis.com')throw new UploadError('YouTube returned an invalid upload location.');
  let upload:Response;try{upload=await fetch(location,{method:'PUT',headers:{'Content-Type':media.type,'Content-Length':String(media.size)},body:media.body,duplex:'half',signal:AbortSignal.timeout(210000),redirect:'error'} as RequestInit&{duplex:'half'});}catch{throw new UploadError('YouTube did not confirm the upload. Check YouTube Studio before trying again.',true);}
  if(!upload.ok)throw new UploadError(`YouTube upload failed (HTTP ${upload.status}).`,upload.status>=500);
  const result=await upload.json().catch(()=>{throw new UploadError('YouTube returned an unreadable upload result. Check YouTube Studio.',true);});if(typeof result?.id!=='string')throw new UploadError('YouTube did not return a video ID. Check YouTube Studio.',true);return result as {id:string;status?:VideoStatus};
 }finally{media.cancel();}
}
export async function getPublicationStatus(id:string,workspaceId:string){
 const {data,error}=await admin().from('publications').select('id,text,state,scheduled_for,created_at,publication_targets(id,state,external_post_id,external_url,error_code,error_message,attempts)').eq('workspace_id',workspaceId).eq('id',id).maybeSingle();
 if(error)throw new Error('ChannelDesk could not read this publication.');
 if(!data)throw new Error('Publication not found in this workspace.');
 return data;
}
async function loadTarget(id:string,workspaceId:string,actorId:string){
 await assertWorkspaceAccess(actorId,workspaceId,true);const db=admin();const {data:pub,error}=await db.from('publications').select('id,state,scheduled_for,updated_at,publication_targets(id,connection_id,external_post_id,state,network_payload)').eq('id',id).eq('workspace_id',workspaceId).maybeSingle();if(error)throw new Error('ChannelDesk could not read this publication.');if(!pub)throw new Error('Publication not found in this workspace.');
 const target=(pub.publication_targets as any[])?.find(t=>t.external_post_id);if(!target)throw new Error('No confirmed YouTube video ID is stored for this publication.');const {data:connection,error:ce}=await db.from('social_connections').select('*').eq('id',target.connection_id).eq('workspace_id',workspaceId).eq('network','youtube').eq('active',true).single();if(ce||!connection)throw new Error('The YouTube connection is unavailable. Reconnect YouTube.');if(!Array.isArray(connection.scopes)||!connection.scopes.includes('https://www.googleapis.com/auth/youtube.force-ssl'))throw new Error('Reconnect YouTube to grant video management permission.');const access=await youtubeAccessToken(connection);
 const r=await fetch(`https://www.googleapis.com/youtube/v3/videos?part=status&id=${encodeURIComponent(target.external_post_id)}`,{headers:{Authorization:`Bearer ${access}`},signal:AbortSignal.timeout(20000),redirect:'error'});if(!r.ok)throw new Error(`YouTube status lookup failed (HTTP ${r.status}).`);const body=await r.json();const status=body.items?.[0]?.status as VideoStatus|undefined;if(!status)throw new Error('This YouTube video is missing or inaccessible.');return {pub,target,access,status,db};
}
export async function syncYouTubePublication(id:string,workspaceId:string,actorId:string){
 const {pub,target,status,db}=await loadTarget(id,workspaceId,actorId);let state=target.state;
 if(['failed','rejected','deleted'].includes(status.uploadStatus||''))state='failed';else if(status.publishAt)state='scheduled';else if(status.uploadStatus==='processed'&&status.privacyStatus===target.network_payload?.privacy)state=target.state==='cancelled'?'cancelled':'published';else if(status.uploadStatus==='processed'&&status.privacyStatus==='public')state='published';
 const {error}=await db.rpc('update_youtube_delivery',{p_publication_id:id,p_target_id:target.id,p_actor_id:actorId,p_state:state,p_scheduled_for:status.publishAt||null,p_error:status.failureReason||status.rejectionReason||null,p_action:'youtube.status_synced',p_expected_updated_at:pub.updated_at});if(error)throw error;return {publicationId:id,videoId:target.external_post_id,state,youtube:status,url:`https://www.youtube.com/watch?v=${target.external_post_id}`};
}
export function assertMutableSchedule(storedState:string,status:VideoStatus){if(storedState!=='scheduled'||status.privacyStatus!=='private'||!status.publishAt||Date.parse(status.publishAt)<=Date.now()+60000)throw new Error('Only a still-private video scheduled more than one minute ahead can be changed.');}
function writableStatus(s:VideoStatus){return {privacyStatus:'private',...(typeof s.selfDeclaredMadeForKids==='boolean'?{selfDeclaredMadeForKids:s.selfDeclaredMadeForKids}:{}),...(typeof s.embeddable==='boolean'?{embeddable:s.embeddable}:{}),...(typeof s.publicStatsViewable==='boolean'?{publicStatsViewable:s.publicStatsViewable}:{}),...(s.license?{license:s.license}:{})};}
async function changeSchedule(id:string,workspaceId:string,actorId:string,date:string|null){
 const {pub,target,status,access,db}=await loadTarget(id,workspaceId,actorId);assertMutableSchedule(pub.state,status);if(date&&(!Number.isFinite(Date.parse(date))||Date.parse(date)<=Date.now()+60000))throw new Error('Choose a schedule at least one minute in the future.');
 // Persist before calling YouTube. A crash leaves needs_review, preventing blind
 // concurrent reschedule/cancel attempts. The status-sync tool can reconcile it.
 const {error:claimError,data:claim}=await db.from('publications').update({state:'needs_review',updated_at:new Date().toISOString()}).eq('id',id).eq('workspace_id',workspaceId).eq('state','scheduled').eq('updated_at',pub.updated_at).select('id,updated_at').maybeSingle();if(claimError||!claim)throw new Error('Another request changed this publication. Refresh its status.');
 try{
  assertMutableSchedule('scheduled',status);
  const nextStatus={...writableStatus(status),...(date?{publishAt:new Date(date).toISOString()}:{})};
  const r=await fetch('https://www.googleapis.com/youtube/v3/videos?part=status',{method:'PUT',headers:{Authorization:`Bearer ${access}`,'Content-Type':'application/json'},body:JSON.stringify({id:target.external_post_id,status:nextStatus}),signal:AbortSignal.timeout(30000),redirect:'error'});
  if(!r.ok){const detail=await r.json().catch(()=>null);const reason=detail?.error?.errors?.[0]?.reason||detail?.error?.message;throw new Error(`YouTube schedule update failed (HTTP ${r.status})${reason?`: ${reason}`:''}.`);}
  const state=date?'scheduled':'cancelled';
  const scheduledFor=date?new Date(date).toISOString():null;
  const {error:persistError}=await db.rpc('update_youtube_delivery',{p_publication_id:id,p_target_id:target.id,p_actor_id:actorId,p_state:state,p_scheduled_for:scheduledFor,p_error:null,p_action:date?'youtube.rescheduled':'youtube.schedule_cancelled',p_expected_updated_at:claim.updated_at});
  if(persistError)throw new Error(`YouTube accepted the schedule change, but ChannelDesk could not save it (${persistError.code||'database_error'}).`);
  return {publicationId:id,videoId:target.external_post_id,state,scheduledFor,youtubePrivacy:'private'};
 }catch(e){logFailure('youtube.schedule_update_failed',e);const message=e instanceof Error?e.message:'The schedule change was not confirmed.';throw new Error(`${message} Sync this video’s status before trying again.`);}
}
export const rescheduleYouTubePublication=(id:string,scheduledFor:string,workspaceId:string,actorId:string)=>changeSchedule(id,workspaceId,actorId,scheduledFor);
export const cancelYouTubeSchedule=(id:string,workspaceId:string,actorId:string)=>changeSchedule(id,workspaceId,actorId,null);


const tiktokPublishInput=z.object({connectionId:z.string().uuid(),caption:z.string().max(2200).default(''),mediaUrl:z.string().url(),privacy:z.enum(['PUBLIC_TO_EVERYONE','MUTUAL_FOLLOW_FRIENDS','FOLLOWER_OF_CREATOR','SELF_ONLY']),disableComment:z.boolean().default(false),disableDuet:z.boolean().default(false),disableStitch:z.boolean().default(false),requestId:z.string().min(8).max(128)}).strict();
const tiktokDraftInput=z.object({connectionId:z.string().uuid(),mediaUrl:z.string().url(),requestId:z.string().min(8).max(128)}).strict();

async function tiktokAccessToken(c:Connection){
 if(c.token_expires_at&&Date.parse(c.token_expires_at)>Date.now()+60000)return decrypt(c.token_ciphertext);
 if(!c.refresh_token_ciphertext)throw new Error('Reconnect TikTok to renew account access.');
 const clientKey=process.env.TIKTOK_CLIENT_KEY,clientSecret=process.env.TIKTOK_CLIENT_SECRET;if(!clientKey||!clientSecret)throw new ConfigurationError('TikTok OAuth credentials');
 const r=await fetch('https://open.tiktokapis.com/v2/oauth/token/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_key:clientKey,client_secret:clientSecret,grant_type:'refresh_token',refresh_token:decrypt(c.refresh_token_ciphertext)}),signal:AbortSignal.timeout(20000),redirect:'error'});
 const t=await r.json().catch(()=>null);if(!r.ok||!t?.access_token||!t?.refresh_token)throw new Error('TikTok could not renew account access. Reconnect TikTok.');
 const scopes=String(t.scope||'').split(',').map((s:string)=>s.trim()).filter(Boolean);const {error}=await admin().from('social_connections').update({token_ciphertext:encrypt(t.access_token),refresh_token_ciphertext:encrypt(t.refresh_token),token_expires_at:t.expires_in?new Date(Date.now()+t.expires_in*1000).toISOString():null,scopes}).eq('id',c.id).eq('workspace_id',c.workspace_id);if(error)throw error;return t.access_token as string;
}
async function tiktokConnection(connectionId:string,workspaceId:string,actorId:string,scope:string){await assertWorkspaceAccess(actorId,workspaceId,true);const {data,error}=await admin().from('social_connections').select('*').eq('id',connectionId).eq('workspace_id',workspaceId).eq('network','tiktok').eq('active',true).maybeSingle();if(error||!data)throw new Error('Choose an active TikTok account in this workspace.');if(!Array.isArray(data.scopes)||!data.scopes.includes(scope))throw new Error(`Reconnect TikTok and approve ${scope} permission.`);return data as Connection;}
export async function getTikTokCreatorInfo(connectionId:string,workspaceId:string,actorId:string){const connection=await tiktokConnection(connectionId,workspaceId,actorId,'video.publish');const access=await tiktokAccessToken(connection);const r=await fetch('https://open.tiktokapis.com/v2/post/publish/creator_info/query/',{method:'POST',headers:{Authorization:`Bearer ${access}`,'Content-Type':'application/json; charset=UTF-8'},body:'{}',signal:AbortSignal.timeout(20000),redirect:'error'});const body=await r.json().catch(()=>null);if(!r.ok||body?.error?.code!=='ok')throw new Error(`TikTok creator lookup failed${body?.error?.code?`: ${body.error.code}`:''}.`);return body.data;}
async function initTikTok(connection:Connection,url:string,endpoint:string,postInfo?:Record<string,unknown>){const access=await tiktokAccessToken(connection);const mediaUrl=validateMediaUrl(url).href;const payload:any={source_info:{source:'PULL_FROM_URL',video_url:mediaUrl}};if(postInfo)payload.post_info=postInfo;const r=await fetch(endpoint,{method:'POST',headers:{Authorization:`Bearer ${access}`,'Content-Type':'application/json; charset=UTF-8'},body:JSON.stringify(payload),signal:AbortSignal.timeout(30000),redirect:'error'});const body=await r.json().catch(()=>null);if(!r.ok||body?.error?.code!=='ok'||!body?.data?.publish_id)throw new Error(`TikTok rejected the post${body?.error?.code?`: ${body.error.code}`:''}${body?.error?.message?` — ${body.error.message}`:''}.`);return body.data;}
export async function publishTikTok(raw:unknown,workspaceId:string,actorId:string){const input=tiktokPublishInput.parse(raw),db=admin();const connection=await tiktokConnection(input.connectionId,workspaceId,actorId,'video.publish');const creator=await getTikTokCreatorInfo(input.connectionId,workspaceId,actorId);if(!creator.privacy_level_options?.includes(input.privacy))throw new Error('That TikTok privacy level is not currently available for this creator.');if(input.disableComment===false&&creator.comment_disabled)throw new Error('Comments are disabled for this TikTok creator.');if(input.disableDuet===false&&creator.duet_disabled)throw new Error('Duet is disabled for this TikTok creator.');if(input.disableStitch===false&&creator.stitch_disabled)throw new Error('Stitch is disabled for this TikTok creator.');const payload={caption:input.caption,mediaUrl:validateMediaUrl(input.mediaUrl).href,privacy:input.privacy,disableComment:input.disableComment,disableDuet:input.disableDuet,disableStitch:input.disableStitch,mode:'direct'};const {data:claim,error:ce}=await db.rpc('claim_tiktok_publication',{p_workspace_id:workspaceId,p_actor_id:actorId,p_connection_id:input.connectionId,p_payload:payload,p_request_id:input.requestId,p_request_hash:hashSecret(JSON.stringify(payload))});if(ce)throw ce;if(claim.idempotentReplay)return {...claim,network:'tiktok'};
 try{const data=await initTikTok(connection,payload.mediaUrl,'https://open.tiktokapis.com/v2/post/publish/video/init/',{title:input.caption,privacy_level:input.privacy,disable_comment:input.disableComment,disable_duet:input.disableDuet,disable_stitch:input.disableStitch,video_cover_timestamp_ms:1000});const {error}=await db.rpc('finish_tiktok_publication',{p_publication_id:claim.publicationId,p_target_id:claim.targetId,p_state:'publishing',p_publish_id:data.publish_id,p_error:null,p_actor_id:actorId});if(error)throw error;return {...claim,network:'tiktok',publishId:data.publish_id,state:'publishing',privacy:input.privacy,creator:{username:creator.creator_username,nickname:creator.creator_nickname},requestId:input.requestId};}catch(e){const message=e instanceof Error?e.message:'TikTok publishing failed.';await db.rpc('finish_tiktok_publication',{p_publication_id:claim.publicationId,p_target_id:claim.targetId,p_state:'failed',p_publish_id:null,p_error:message,p_actor_id:actorId});throw e;}}
export async function uploadTikTokDraft(raw:unknown,workspaceId:string,actorId:string){const input=tiktokDraftInput.parse(raw),db=admin();const connection=await tiktokConnection(input.connectionId,workspaceId,actorId,'video.upload');const payload={caption:'',mediaUrl:validateMediaUrl(input.mediaUrl).href,mode:'draft'};const {data:claim,error:ce}=await db.rpc('claim_tiktok_publication',{p_workspace_id:workspaceId,p_actor_id:actorId,p_connection_id:input.connectionId,p_payload:payload,p_request_id:input.requestId,p_request_hash:hashSecret(JSON.stringify(payload))});if(ce)throw ce;if(claim.idempotentReplay)return {...claim,network:'tiktok'};try{const data=await initTikTok(connection,payload.mediaUrl,'https://open.tiktokapis.com/v2/post/publish/inbox/video/init/');const {error}=await db.rpc('finish_tiktok_publication',{p_publication_id:claim.publicationId,p_target_id:claim.targetId,p_state:'publishing',p_publish_id:data.publish_id,p_error:null,p_actor_id:actorId});if(error)throw error;return {...claim,network:'tiktok',publishId:data.publish_id,state:'publishing',requestId:input.requestId};}catch(e){const message=e instanceof Error?e.message:'TikTok draft upload failed.';await db.rpc('finish_tiktok_publication',{p_publication_id:claim.publicationId,p_target_id:claim.targetId,p_state:'failed',p_publish_id:null,p_error:message,p_actor_id:actorId});throw e;}}
export async function getTikTokPostStatus(connectionId:string,publishId:string,workspaceId:string,actorId:string){const connection=await tiktokConnection(connectionId,workspaceId,actorId,'video.publish');const access=await tiktokAccessToken(connection);const r=await fetch('https://open.tiktokapis.com/v2/post/publish/status/fetch/',{method:'POST',headers:{Authorization:`Bearer ${access}`,'Content-Type':'application/json; charset=UTF-8'},body:JSON.stringify({publish_id:publishId}),signal:AbortSignal.timeout(20000),redirect:'error'});const body=await r.json().catch(()=>null);if(!r.ok||body?.error?.code!=='ok')throw new Error(`TikTok status lookup failed${body?.error?.code?`: ${body.error.code}`:''}.`);const data=body.data,status=String(data?.status||''),state=status==='PUBLISH_COMPLETE'?'published':status==='FAILED'?'failed':'publishing';const db=admin();const {data:target}=await db.from('publication_targets').select('id,publication_id,publications!inner(workspace_id)').eq('connection_id',connectionId).eq('external_post_id',publishId).eq('publications.workspace_id',workspaceId).maybeSingle();if(target){const {error}=await db.rpc('finish_tiktok_publication',{p_publication_id:target.publication_id,p_target_id:target.id,p_state:state,p_publish_id:publishId,p_error:status==='FAILED'?(data?.fail_reason||'TikTok processing failed.'):null,p_actor_id:actorId});if(error)logFailure('tiktok.status_persist_failed',error);}return {...data,state};}
