import Link from "next/link";
import {createClient} from "@/lib/supabase/server";
import MediaUploader from "./media-uploader";
import MediaGenerationStatus from "./media-generation-status";
export default async function Media(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return null;
 const {data:m}=await supabase.from("workspace_members").select("workspace_id").eq("user_id",user.id).limit(1).maybeSingle();if(!m)return <div className="panel empty"><b>No workspace found</b></div>;
 const {data:assets,error}=await supabase.from("media_assets").select("id,storage_key,mime_type,width,height,duration_ms,source_url,rights_basis,created_at").eq("workspace_id",m.workspace_id).order("created_at",{ascending:false}).limit(100);if(error)throw error;
 return <><div className="page-title"><div><p className="eyebrow">MEDIA</p><h1>Media library</h1><p className="muted">Reusable workspace media with source and rights provenance.</p></div><Link className="button" href="/create">Create post</Link></div><MediaUploader workspaceId={m.workspace_id}/><MediaGenerationStatus workspaceId={m.workspace_id}/>{!assets?.length?<div className="panel empty"><b>Your library is empty</b><span>Upload media above and it will be stored privately in your workspace, ready for publishing through ChannelDesk.</span><span>Your uploaded assets will appear here.</span></div>:<div className="media-grid">{assets.map(a=><article className="panel media-card" key={a.id}><div className="media-preview">{a.source_url&&a.mime_type.startsWith("video/")?<video src={"/media/"+a.id} preload="metadata" controls/>:<span>{a.mime_type.split("/")[0].toUpperCase()}</span>}</div><div className="media-meta"><b>{a.storage_key.split("/").pop()||"Media asset"}</b><span>{a.mime_type}{a.width&&a.height?" · "+a.width+"×"+a.height:""}{a.duration_ms?" · "+Math.round(a.duration_ms/1000)+"s":""}</span><span>Added {new Date(a.created_at).toLocaleDateString("en-GB")}</span>{a.rights_basis?<small>Rights: {a.rights_basis}</small>:null}<div className="media-actions"><Link href="/create">Use in post</Link>{a.source_url?<a href={"/media/"+a.id} target="_blank" rel="noreferrer">Preview ↗</a>:null}</div></div></article>)}</div>}</>;
}