import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {readFile,readdir} from 'node:fs/promises';
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',ANALYST='33333333-3333-4333-8333-333333333333',EDITOR='44444444-4444-4444-8444-444444444444';
const WA='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',WB='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',CA='cccccccc-cccc-4ccc-8ccc-cccccccccccc',CB='dddddddd-dddd-4ddd-8ddd-dddddddddddd';
test('database boundaries and atomic OAuth/publication operations',async t=>{
 const db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create function auth.uid() returns uuid language sql stable as $auth$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $auth$;grant usage on schema auth,public to anon,authenticated,service_role;grant execute on function auth.uid() to anon,authenticated,service_role;create schema storage;create table storage.buckets(id text primary key,name text not null,public boolean not null default false,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text not null,name text not null);create function storage.foldername(name text) returns text[] language sql immutable as $storage$ select string_to_array(name,'/') $storage$;grant usage on schema storage to authenticated,service_role;grant select,insert,update,delete on storage.buckets,storage.objects to authenticated,service_role;`);
 for(const file of (await readdir('supabase/migrations')).filter(s=>s.endsWith('.sql')).sort()){const sql=(await readFile('supabase/migrations/'+file,'utf8')).replace('create extension if not exists pgcrypto;','');await db.exec(sql);}
 await db.exec(await readFile('scripts/verify-database.sql','utf8'));
 await db.exec(`insert into workspaces(id,name,slug) values('${WA}','A','workspace-a'),('${WB}','B','workspace-b');insert into workspace_members values('${WA}','${A}','owner'),('${WB}','${B}','owner'),('${WA}','${ANALYST}','analyst'),('${WA}','${EDITOR}','editor');insert into social_connections(id,workspace_id,network,external_account_id,display_name,token_ciphertext) values('${CA}','${WA}','youtube','remote-a','Channel A','encrypted-a'),('${CB}','${WB}','youtube','remote-b','Channel B','encrypted-b');insert into media_assets(workspace_id,storage_key,mime_type) values('${WA}','a','video/mp4'),('${WB}','b','video/mp4');insert into publications(workspace_id,author_id,text) values('${WA}','${A}','A content'),('${WB}','${B}','B content');insert into audit_events(workspace_id,action,entity_type) values('${WA}','a','test'),('${WB}','b','test');`);
 const as=async(role:string,user=A)=>{await db.exec(`reset role;set role ${role};select set_config('request.jwt.claim.sub','${user}',false);`);};
 await t.test('members see only rows in their workspace, never channel credentials',async()=>{await as('authenticated');for(const table of ['workspaces','social_connections','media_assets','publications','audit_events']){const result=await db.query(`select id from ${table}`);assert.equal(result.rows.length,1,table);}await assert.rejects(()=>db.query('select token_ciphertext from social_connections'),/permission denied/);await assert.rejects(()=>db.query(`insert into media_assets(workspace_id,storage_key,mime_type) values('${WB}','bad','video/mp4')`),/row-level security/);});
 await t.test('unauthenticated and browser users cannot mint or exchange MCP grants',async()=>{await as('authenticated');await assert.rejects(()=>db.query("select issue_mcp_oauth_code('a','b','c','d','e','f',now())"),/permission denied/);await as('anon');await assert.rejects(()=>db.query("select exchange_mcp_oauth_code('a','b','c','d','e','f','g')"),/permission denied/);});
 await as('service_role');
 await t.test('invalid PKCE does not consume code; concurrent valid redemption has one winner',async()=>{await db.query('insert into mcp_oauth_codes(code_hash,user_id,client_id,redirect_uri,resource,scope,code_challenge,expires_at) values($1,$2,$3,$4,$5,$6,$7,now()+interval \'5 minutes\')',['code',A,'client','redirect','resource','channeldesk.read','challenge']);await assert.rejects(()=>db.query("select exchange_mcp_oauth_code('code','client','redirect','resource','wrong','a','r')"),/Invalid grant/);const results=await Promise.allSettled([db.query("select exchange_mcp_oauth_code('code','client','redirect','resource','challenge','access1','refresh1')"),db.query("select exchange_mcp_oauth_code('code','client','redirect','resource','challenge','access2','refresh2')")]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await db.query('select * from mcp_oauth_tokens')).rows.length,2);});
 await t.test('refresh cannot escalate scope or be replayed',async()=>{await assert.rejects(()=>db.query("select rotate_mcp_oauth_token('refresh1','client','resource','channeldesk.publish','a2','r2')"),/Invalid scope/);await db.query("select rotate_mcp_oauth_token('refresh1','client','resource',null,'a2','r2')");await assert.rejects(()=>db.query("select rotate_mcp_oauth_token('refresh1','client','resource',null,'a3','r3')"),/Invalid grant/);});
 let claim:any;
 await t.test('idempotent publication creation is atomic and records the real actor',async()=>{const args=[WA,A,CA,JSON.stringify({title:'Test',description:'Saved',privacy:'private'}),'request-123','request-hash'];const results=await Promise.all([db.query('select claim_youtube_publication($1,$2,$3,$4,$5,$6) as value',args),db.query('select claim_youtube_publication($1,$2,$3,$4,$5,$6) as value',args)]);const values=results.map(r=>(r.rows[0] as any).value);assert.equal(values.filter(v=>!v.idempotentReplay).length,1);assert.equal(values[0].publicationId,values[1].publicationId);claim=values[0];const row=await db.query('select author_id from publications where id=$1',[claim.publicationId]);assert.equal((row.rows[0] as any).author_id,A);await assert.rejects(()=>db.query('select claim_youtube_publication($1,$2,$3,$4,$5,$6)',[...args.slice(0,5),'different-hash']),/different content/);});
 await t.test('analysts and cross-workspace connections cannot publish',async()=>{const payload=JSON.stringify({title:'test'});await assert.rejects(()=>db.query('select claim_youtube_publication($1,$2,$3,$4,$5,$6)',[WA,ANALYST,CA,payload,'analyst-request','hash']),/Publishing role/);await assert.rejects(()=>db.query('select claim_youtube_publication($1,$2,$3,$4,$5,$6)',[WA,A,CB,payload,'wrong-connection','hash']),/Invalid channel/);await assert.rejects(()=>db.query('insert into publication_targets(publication_id,connection_id,idempotency_key) values($1,$2,$3)',[claim.publicationId,CB,'cross-workspace']),/same workspace/);});
 await t.test('draft approval workflow is atomic and editors cannot approve their own request',async()=>{await as('authenticated',EDITOR);const media=await db.query('select id from media_assets where workspace_id=$1 limit 1',[WA]);const mediaId=(media.rows[0] as any).id;const draft=await db.query('select create_publication_draft($1,$2,$3,$4) as id',[CA,mediaId,'Review me',JSON.stringify({title:'Review me'})]);const publicationId=(draft.rows[0] as any).id;const approval=await db.query('select request_publication_approval($1,$2) as id',[publicationId,'Please review']);const approvalId=(approval.rows[0] as any).id;await assert.rejects(()=>db.query('select decide_publication_approval($1,$2,$3)',[approvalId,'approved',null]),/not_authorized/);await as('authenticated',A);await db.query('select decide_publication_approval($1,$2,$3)',[approvalId,'approved','Looks good']);const p=await db.query('select state from publications where id=$1',[publicationId]);assert.equal((p.rows[0] as any).state,'draft');const a=await db.query('select state,reviewer_id from approval_requests where id=$1',[approvalId]);assert.equal((a.rows[0] as any).state,'approved');assert.equal((a.rows[0] as any).reviewer_id,A);});
 await t.test('delivery completion updates publication and target together and writes an audit',async()=>{await db.query('select finish_youtube_publication($1,$2,$3,$4,$5,$6)',[claim.publicationId,claim.targetId,'published','video-id',null,A]);const p=await db.query('select state from publications where id=$1',[claim.publicationId]);assert.equal((p.rows[0] as any).state,'published');const a=await db.query("select id from audit_events where entity_id=$1 and action='youtube.published'",[claim.publicationId]);assert.equal(a.rows.length,1);await assert.rejects(()=>db.query('select finish_youtube_publication($1,$2,$3,$4,$5,$6)',[claim.publicationId,claim.targetId,'failed',null,'late error',A]),/state changed/);});
 await db.close();
});
