'use server';
import {admin} from '@/lib/mcp-oauth';
import {changePlannerSchedule} from '@/lib/scheduling';
import {revalidatePath} from 'next/cache';import {redirect} from 'next/navigation';import {createClient} from '@/lib/supabase/server';
async function db(){const s=await createClient();const {data:{user}}=await s.auth.getUser();if(!user)throw new Error('Sign in to continue.');return {s,user};}
export async function requestApproval(formData:FormData){const {s}=await db();const id=String(formData.get('publicationId')||'');const {error}=await s.rpc('request_publication_approval',{p_publication_id:id,p_note:String(formData.get('note')||'')||null});redirect('/planner?'+(error?'error='+encodeURIComponent(error.message):'message='+encodeURIComponent('Sent for approval.')));}
export async function decideApproval(formData:FormData){const {s}=await db();const requestId=String(formData.get('requestId')||''),decision=String(formData.get('decision')||'');if(!['approved','rejected'].includes(decision))redirect('/planner?error='+encodeURIComponent('Choose approve or reject.'));const {error}=await s.rpc('decide_publication_approval',{p_request_id:requestId,p_decision:decision,p_note:String(formData.get('note')||'')||null});redirect('/planner?'+(error?'error='+encodeURIComponent(error.message):'message='+encodeURIComponent(decision==='approved'?'Content approved.':'Changes requested.')));}

async function publicationContext(publicationId:string){const {s,user}=await db();const {data:p,error}=await s.from('publications').select('workspace_id').eq('id',publicationId).maybeSingle();if(error||!p)throw new Error('Publication not found.');return {userId:user.id,workspaceId:p.workspace_id};}
export async function reschedulePlannerPublication(publicationId:string,scheduledFor:string){const c=await publicationContext(publicationId);const result=await changePlannerSchedule(publicationId,c.workspaceId,c.userId,scheduledFor);revalidatePath('/planner');return result;}
export async function updatePlannerDraft(publicationId:string,text:string){const c=await publicationContext(publicationId);const clean=text.trim();const {error}=await admin().rpc('edit_planner_draft',{p_publication_id:publicationId,p_workspace_id:c.workspaceId,p_actor_id:c.userId,p_text:clean});if(error)throw new Error(error.code==='22023'?error.message:'This draft could not be edited.');revalidatePath('/planner');return {id:publicationId,text:clean};}
