"use server";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
function safeNext(v:FormDataEntryValue|null){const s=String(v??"/");return s.startsWith("/")&&!s.startsWith("//")?s:"/";}
export async function signIn(formData:FormData){const email=String(formData.get("email")??"").trim(),password=String(formData.get("password")??""),next=safeNext(formData.get("next"));const supabase=await createClient();const {error}=await supabase.auth.signInWithPassword({email,password});if(error) redirect("/login?error="+encodeURIComponent(error.message)+"&next="+encodeURIComponent(next));redirect(next);}
export async function signUp(formData:FormData){const email=String(formData.get("email")??"").trim(),password=String(formData.get("password")??"");const supabase=await createClient();const {error}=await supabase.auth.signUp({email,password});if(error) redirect("/login?error="+encodeURIComponent(error.message));redirect("/login?message="+encodeURIComponent("Check your email to confirm your account."));}
export async function signInWithGoogle(formData:FormData){const next=safeNext(formData.get("next"));const supabase=await createClient();const h=await headers();const origin=h.get("origin")??process.env.NEXT_PUBLIC_APP_URL??"http://localhost:3000";const {data,error}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${origin}/auth/callback?next=${encodeURIComponent(next)}`}});if(error) redirect("/login?error="+encodeURIComponent(error.message)+"&next="+encodeURIComponent(next));if(!data.url) redirect("/login?error="+encodeURIComponent("Google sign-in could not be started."));redirect(data.url);}
export async function signOut(){const supabase=await createClient();await supabase.auth.signOut();redirect("/login");}
