import React,{useState}from'react';
import{SafeAreaView,View,Text,TextInput,TouchableOpacity,StyleSheet,Alert,KeyboardAvoidingView,Platform}from'react-native';
import{Ionicons}from'@expo/vector-icons';
import{createUserWithEmailAndPassword,signInWithEmailAndPassword,signInWithCredential,GoogleAuthProvider}from'firebase/auth';
import{GoogleSignin,statusCodes}from'@react-native-google-signin/google-signin';
import{auth}from'./firebase';

export default function AuthScreen(){
 const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[mode,setMode]=useState('signin'),[busy,setBusy]=useState(false);
 const submit=async()=>{if(!email.trim()||password.length<6)return Alert.alert('Check your details','Enter your email and a password of at least 6 characters.');try{setBusy(true);if(mode==='signup')await createUserWithEmailAndPassword(auth,email.trim(),password);else await signInWithEmailAndPassword(auth,email.trim(),password)}catch(e){Alert.alert(mode==='signup'?'Create account':'Sign in',e.message)}finally{setBusy(false)}};
 const google=async()=>{try{setBusy(true);await GoogleSignin.hasPlayServices({showPlayServicesUpdateDialog:true});const r=await GoogleSignin.signIn();const token=r?.data?.idToken||r?.idToken;if(!token)throw new Error('Google did not return an ID token.');await signInWithCredential(auth,GoogleAuthProvider.credential(token))}catch(e){if(e?.code!==statusCodes.SIGN_IN_CANCELLED)Alert.alert('Google Sign-In',e?.message||'Unable to sign in.')}finally{setBusy(false)}};
 return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={s.page} behavior={Platform.OS==='ios'?'padding':undefined}><View style={s.brand}><View style={s.mark}><Ionicons name="bag-handle" size={30} color="#fff"/></View><Text style={s.logo}>WhatBuy</Text><Text style={s.tag}>Buy. Sell. Chat.</Text></View><View style={s.card}><Text style={s.title}>{mode==='signup'?'Create your account':'Welcome back'}</Text><Text style={s.sub}>{mode==='signup'?'Join the marketplace in seconds.':'Sign in to continue to WhatBuy.'}</Text><Text style={s.label}>Email</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" autoComplete="email" placeholder="you@example.com" style={s.input}/><Text style={s.label}>Password</Text><TextInput value={password} onChangeText={setPassword} secureTextEntry autoComplete={mode==='signup'?'new-password':'password'} placeholder="••••••••" style={s.input}/><TouchableOpacity disabled={busy} style={[s.primary,busy&&s.disabled]} onPress={submit}><Text style={s.primaryText}>{busy?'Please wait…':mode==='signup'?'Create account':'Sign in'}</Text></TouchableOpacity><View style={s.or}><View style={s.line}/><Text style={s.orText}>or</Text><View style={s.line}/></View><TouchableOpacity disabled={busy} style={s.google} onPress={google}><Ionicons name="logo-google" size={20}/><Text style={s.googleText}>Continue with Google</Text></TouchableOpacity><TouchableOpacity onPress={()=>setMode(mode==='signup'?'signin':'signup')}><Text style={s.switch}>{mode==='signup'?'Already have an account? Sign in':'New to WhatBuy? Create account'}</Text></TouchableOpacity></View><Text style={s.legal}>By continuing you agree to WhatBuy’s Terms and Privacy Policy.</Text></KeyboardAvoidingView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7FAF8'},page:{flex:1,justifyContent:'center',padding:22},brand:{alignItems:'center',marginBottom:28},mark:{width:62,height:62,borderRadius:20,backgroundColor:'#0A8F5A',alignItems:'center',justifyContent:'center',marginBottom:12},logo:{fontSize:34,fontWeight:'900',letterSpacing:-1.2,color:'#101828'},tag:{color:'#667085',marginTop:2},card:{backgroundColor:'#fff',borderRadius:24,padding:22,borderWidth:1,borderColor:'#EAECF0'},title:{fontSize:25,fontWeight:'900',color:'#101828'},sub:{color:'#667085',marginTop:5,marginBottom:20},label:{fontWeight:'800',marginBottom:7,marginTop:10,color:'#344054'},input:{height:52,borderWidth:1,borderColor:'#D0D5DD',borderRadius:14,paddingHorizontal:14,backgroundColor:'#fff'},primary:{height:54,borderRadius:15,backgroundColor:'#0A8F5A',alignItems:'center',justifyContent:'center',marginTop:20},disabled:{opacity:.65},primaryText:{color:'#fff',fontWeight:'900',fontSize:16},or:{flexDirection:'row',alignItems:'center',gap:10,marginVertical:16},line:{height:1,backgroundColor:'#EAECF0',flex:1},orText:{color:'#98A2B3'},google:{height:52,borderRadius:15,borderWidth:1,borderColor:'#D0D5DD',flexDirection:'row',alignItems:'center',justifyContent:'center',gap:10},googleText:{fontWeight:'800'},switch:{textAlign:'center',color:'#087A4D',fontWeight:'800',paddingTop:18},legal:{fontSize:11,color:'#98A2B3',textAlign:'center',marginTop:18,lineHeight:16}});