import React,{useEffect,useMemo,useRef,useState}from'react';
import{View,Text,StyleSheet,TouchableOpacity,FlatList,TextInput,Image,Alert,KeyboardAvoidingView,Platform}from'react-native';
import{Ionicons}from'@expo/vector-icons';
import{addDoc,collection,deleteDoc,doc,onSnapshot,orderBy,query,serverTimestamp,updateDoc}from'firebase/firestore';
import{db}from'./firebase';

const time=t=>{const d=t?.toDate?.();return d?d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):''};
export default function ChatScreen({chat,user,onClose}){
 const[messages,setMessages]=useState([]),[text,setText]=useState(''),[reply,setReply]=useState(null),[typing,setTyping]=useState(false),[otherTyping,setOtherTyping]=useState(false),[menu,setMenu]=useState(null);const list=useRef(null),timer=useRef(null);
 const otherId=useMemo(()=>chat?.participantIds?.find(x=>x!==user.uid),[chat,user]);
 useEffect(()=>{if(!chat)return;const unsub=onSnapshot(query(collection(db,'chats',chat.id,'messages'),orderBy('createdAt','asc')),snap=>setMessages(snap.docs.map(d=>({id:d.id,...d.data()}))));return unsub},[chat]);
 useEffect(()=>{if(!chat)return;const unsub=onSnapshot(doc(db,'chats',chat.id),snap=>{const d=snap.data()||{};setOtherTyping(!!d.typing?.[otherId]);const unread=d.unreadCount?.[user.uid]||0;if(unread>0)updateDoc(snap.ref,{['unreadCount.'+user.uid]:0,['lastReadAt.'+user.uid]:serverTimestamp()}).catch(()=>{})});return unsub},[chat,otherId,user.uid]);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);if(chat)updateDoc(doc(db,'chats',chat.id),{['typing.'+user.uid]:false}).catch(()=>{})},[chat,user.uid]);
 const type=v=>{setText(v);if(!typing){setTyping(true);updateDoc(doc(db,'chats',chat.id),{['typing.'+user.uid]:true}).catch(()=>{})}if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>{setTyping(false);updateDoc(doc(db,'chats',chat.id),{['typing.'+user.uid]:false}).catch(()=>{})},1200)};
 const send=async()=>{const body=text.trim();if(!body)return;setText('');setReply(null);try{await addDoc(collection(db,'chats',chat.id,'messages'),{senderId:user.uid,type:'text',text:body,replyTo:reply?{id:reply.id,text:reply.text||'',senderId:reply.senderId}:null,createdAt:serverTimestamp(),editedAt:null,deletedForEveryone:false,reactions:{}});await updateDoc(doc(db,'chats',chat.id),{lastMessage:body,lastMessageSenderId:user.uid,updatedAt:serverTimestamp(),['unreadCount.'+otherId]:(chat.unreadCount?.[otherId]||0)+1,['typing.'+user.uid]:false});setTyping(false)}catch(e){setText(body);Alert.alert('Message',e.message)}};
 const react=async(m,emoji)=>{try{await updateDoc(doc(db,'chats',chat.id,'messages',m.id),{['reactions.'+user.uid]:emoji});setMenu(null)}catch(e){Alert.alert('Reaction',e.message)}};
 const remove=async m=>{if(m.senderId!==user.uid)return;try{await updateDoc(doc(db,'chats',chat.id,'messages',m.id),{text:'',deletedForEveryone:true,deletedAt:serverTimestamp()});setMenu(null)}catch(e){Alert.alert('Delete',e.message)}};
 return <KeyboardAvoidingView style={s.page} behavior={Platform.OS==='ios'?'padding':undefined}>
  <View style={s.head}><TouchableOpacity style={s.back} onPress={onClose}><Ionicons name="arrow-back" size={25}/></TouchableOpacity>{chat.listingImage?<Image source={{uri:chat.listingImage}} style={s.avatar}/>:<View style={s.avatarEmpty}><Ionicons name="person" size={22} color="#087A4D"/></View>}<View style={{flex:1}}><Text numberOfLines={1} style={s.name}>{chat.listingTitle||'WhatBuy chat'}</Text><Text style={s.status}>{otherTyping?'typing…':'Marketplace conversation'}</Text></View><TouchableOpacity style={s.iconBtn}><Ionicons name="search-outline" size={22}/></TouchableOpacity><TouchableOpacity style={s.iconBtn}><Ionicons name="ellipsis-vertical" size={22}/></TouchableOpacity></View>
  <FlatList ref={list} data={messages} keyExtractor={x=>x.id} contentContainerStyle={s.messages} onContentSizeChange={()=>list.current?.scrollToEnd({animated:true})} renderItem={({item})=>{const mine=item.senderId===user.uid;return <TouchableOpacity activeOpacity=.9 onLongPress={()=>setMenu(item)} style={[s.bubble,mine?s.mine:s.theirs]}>{item.replyTo&&<View style={s.quote}><Text numberOfLines={1} style={s.quoteText}>{item.replyTo.text||'Message'}</Text></View>}<Text style={mine?s.mineText:s.theirText}>{item.deletedForEveryone?'This message was deleted':item.text}</Text><View style={s.meta}>{item.editedAt&&<Text style={mine?s.mineMeta:s.theirMeta}>edited · </Text>}<Text style={mine?s.mineMeta:s.theirMeta}>{time(item.createdAt)}</Text>{mine&&<Ionicons name="checkmark-done" size={15} color={chat.lastReadAt?.[otherId]?'#BDEBD8':'#D0F0E2'}/>}</View>{item.reactions&&Object.values(item.reactions).length>0&&<View style={s.reaction}><Text>{Object.values(item.reactions).join(' ')}</Text></View>}</TouchableOpacity>}}/>
  {menu&&<View style={s.menu}><TouchableOpacity onPress={()=>{setReply(menu);setMenu(null)}}><Text style={s.menuText}>Reply</Text></TouchableOpacity>{['👍','❤️','😂','😮','😢','🙏'].map(e=><TouchableOpacity key={e} onPress={()=>react(menu,e)}><Text style={s.emoji}>{e}</Text></TouchableOpacity>)}{menu.senderId===user.uid&&<TouchableOpacity onPress={()=>remove(menu)}><Ionicons name="trash-outline" size={20} color="#B42318"/></TouchableOpacity>}<TouchableOpacity onPress={()=>setMenu(null)}><Ionicons name="close" size={20}/></TouchableOpacity></View>}
  {reply&&<View style={s.reply}><View style={{flex:1}}><Text style={s.replyLabel}>Replying to {reply.senderId===user.uid?'yourself':'message'}</Text><Text numberOfLines={1} style={s.replyText}>{reply.text}</Text></View><TouchableOpacity onPress={()=>setReply(null)}><Ionicons name="close" size={20}/></TouchableOpacity></View>}
  <View style={s.composer}><TouchableOpacity style={s.round}><Ionicons name="add" size={24} color="#087A4D"/></TouchableOpacity><View style={s.inputWrap}><TextInput value={text} onChangeText={type} multiline maxLength={4000} placeholder="Message" style={s.input}/><TouchableOpacity><Ionicons name="camera-outline" size={22} color="#667085"/></TouchableOpacity></View><TouchableOpacity style={s.send} onPress={send}><Ionicons name={text.trim()?'send':'mic'} size={21} color="#fff"/></TouchableOpacity></View>
 </KeyboardAvoidingView>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F5F7F6'},head:{height:64,backgroundColor:'#fff',flexDirection:'row',alignItems:'center',gap:9,paddingHorizontal:8,borderBottomWidth:1,borderColor:'#EAECF0'},back:{padding:7},avatar:{width:40,height:40,borderRadius:20},avatarEmpty:{width:40,height:40,borderRadius:20,backgroundColor:'#EAF9F2',alignItems:'center',justifyContent:'center'},name:{fontWeight:'900',fontSize:16},status:{fontSize:11,color:'#667085',marginTop:2},iconBtn:{padding:7},messages:{padding:12,paddingBottom:18},bubble:{maxWidth:'82%',paddingHorizontal:11,paddingTop:8,paddingBottom:6,borderRadius:13,marginVertical:3,position:'relative'},mine:{alignSelf:'flex-end',backgroundColor:'#0A8F5A',borderBottomRightRadius:3},theirs:{alignSelf:'flex-start',backgroundColor:'#fff',borderBottomLeftRadius:3},mineText:{color:'#fff',fontSize:15,lineHeight:20},theirText:{color:'#111827',fontSize:15,lineHeight:20},meta:{flexDirection:'row',alignItems:'center',alignSelf:'flex-end',gap:3,marginTop:3},mineMeta:{color:'#D0F0E2',fontSize:10},theirMeta:{color:'#98A2B3',fontSize:10},quote:{borderLeftWidth:3,borderLeftColor:'#68D6A7',backgroundColor:'rgba(255,255,255,.13)',borderRadius:6,padding:6,marginBottom:5},quoteText:{fontSize:12,color:'#667085'},reaction:{position:'absolute',bottom:-14,right:4,backgroundColor:'#fff',borderRadius:12,paddingHorizontal:6,paddingVertical:2,elevation:2},menu:{minHeight:48,backgroundColor:'#fff',borderTopWidth:1,borderColor:'#EAECF0',flexDirection:'row',alignItems:'center',gap:11,paddingHorizontal:12},menuText:{fontWeight:'800',color:'#087A4D'},emoji:{fontSize:20},reply:{backgroundColor:'#fff',borderTopWidth:1,borderColor:'#EAECF0',paddingHorizontal:14,paddingVertical:8,flexDirection:'row',alignItems:'center'},replyLabel:{fontSize:11,fontWeight:'900',color:'#087A4D'},replyText:{color:'#667085',fontSize:12,marginTop:2},composer:{backgroundColor:'#fff',padding:8,flexDirection:'row',alignItems:'flex-end',gap:7,borderTopWidth:1,borderColor:'#EAECF0'},round:{width:42,height:42,borderRadius:21,backgroundColor:'#EAF9F2',alignItems:'center',justifyContent:'center'},inputWrap:{flex:1,minHeight:42,maxHeight:110,borderRadius:22,backgroundColor:'#F2F4F7',paddingHorizontal:13,flexDirection:'row',alignItems:'center'},input:{flex:1,paddingVertical:10},send:{width:42,height:42,borderRadius:21,backgroundColor:'#0A8F5A',alignItems:'center',justifyContent:'center'}});
