import React,{useEffect,useState}from'react';
import{View,Text,StyleSheet,TouchableOpacity,TextInput,Modal,Alert}from'react-native';
import{collection,onSnapshot,query,where}from'firebase/firestore';
import{db}from'./firebase';
import{respondToOffer,createOrder}from'./commerce';

export default function OffersInbox({user,onOrderCreated}){
 const[offers,setOffers]=useState([]),[counter,setCounter]=useState(null),[amount,setAmount]=useState('');
 useEffect(()=>{if(!user){setOffers([]);return}return onSnapshot(query(collection(db,'offers'),where('participantIds','array-contains',user.uid)),snap=>{const rows=snap.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.status==='pending'||x.status==='countered');rows.sort((a,b)=>(b.updatedAt?.seconds||0)-(a.updatedAt?.seconds||0));setOffers(rows)},e=>console.log('Offers:',e.message))},[user]);
 if(!user||!offers.length)return null;
 const act=async(o,action)=>{try{await respondToOffer({offerId:o.id,userId:user.uid,action});if(action==='accept'){const listing={id:o.listingId,title:o.listingTitle,img:o.listingImage,sellerId:o.sellerId,price:o.amount/100};await createOrder({listing,buyer:{uid:o.buyerId},offer:o});onOrderCreated?.()} }catch(e){Alert.alert('Offer',e.message)}};
 const sendCounter=async()=>{try{await respondToOffer({offerId:counter.id,userId:user.uid,action:'counter',counterAmountPounds:amount});setCounter(null);setAmount('')}catch(e){Alert.alert('Counter offer',e.message)}};
 return <View style={s.wrap}><Text style={s.heading}>Offers</Text>{offers.slice(0,4).map(o=>{const seller=o.sellerId===user.uid;return <View key={o.id} style={s.card}><View style={{flex:1}}><Text numberOfLines={1} style={s.title}>{o.listingTitle}</Text><Text style={s.price}>£{(o.amount/100).toFixed(2)}</Text><Text style={s.meta}>{seller?'Offer received':'Your offer'} · {o.status}</Text></View><View style={s.actions}>{seller&&o.status==='pending'?<TouchableOpacity style={s.accept} onPress={()=>act(o,'accept')}><Text style={s.acceptText}>Accept</Text></TouchableOpacity>:null}<TouchableOpacity style={s.counter} onPress={()=>{setCounter(o);setAmount('')}}><Text style={s.counterText}>Counter</Text></TouchableOpacity>{seller&&o.status==='pending'?<TouchableOpacity onPress={()=>act(o,'decline')}><Text style={s.decline}>Decline</Text></TouchableOpacity>:null}</View></View>})}<Modal visible={!!counter} transparent animationType="fade" onRequestClose={()=>setCounter(null)}><View style={s.overlay}><View style={s.sheet}><Text style={s.heading}>Counter offer</Text><Text style={s.meta}>Enter the price you want to propose.</Text><TextInput value={amount} onChangeText={setAmount} keyboardType="decimal-pad" placeholder="£0.00" style={s.input}/><TouchableOpacity style={s.accept} onPress={sendCounter}><Text style={s.acceptText}>Send counter</Text></TouchableOpacity><TouchableOpacity style={s.cancel} onPress={()=>setCounter(null)}><Text>Cancel</Text></TouchableOpacity></View></View></Modal></View>
}
const s=StyleSheet.create({wrap:{paddingHorizontal:14,paddingTop:10},heading:{fontSize:18,fontWeight:'900'},card:{marginTop:10,borderWidth:1,borderColor:'#EAECF0',borderRadius:16,padding:12,flexDirection:'row',gap:10},title:{fontWeight:'900'},price:{fontWeight:'900',fontSize:17,marginTop:3},meta:{color:'#667085',fontSize:12,marginTop:3},actions:{alignItems:'flex-end',gap:6},accept:{backgroundColor:'#0A8F5A',borderRadius:12,paddingHorizontal:14,paddingVertical:9,alignItems:'center'},acceptText:{color:'#fff',fontWeight:'900'},counter:{borderWidth:1,borderColor:'#0A8F5A',borderRadius:12,paddingHorizontal:12,paddingVertical:7},counterText:{color:'#087A4D',fontWeight:'800'},decline:{color:'#B42318',fontWeight:'800',padding:4},overlay:{flex:1,backgroundColor:'rgba(0,0,0,.35)',justifyContent:'center',padding:22},sheet:{backgroundColor:'#fff',borderRadius:20,padding:20,gap:12},input:{borderWidth:1,borderColor:'#D0D5DD',borderRadius:14,paddingHorizontal:14,height:50},cancel:{height:42,alignItems:'center',justifyContent:'center'}});