import React,{useEffect,useState}from'react';
import{View,Text,StyleSheet,TouchableOpacity,TextInput,Modal,Alert,Image}from'react-native';
import{collection,onSnapshot,query,where}from'firebase/firestore';
import{db}from'./firebase';
import{respondToOffer,createOrder}from'./commerce';
export default function OffersInbox({user,onOrderCreated}){
 const[offers,setOffers]=useState([]),[counter,setCounter]=useState(null),[amount,setAmount]=useState('');
 useEffect(()=>{if(!user){setOffers([]);return}return onSnapshot(query(collection(db,'offers'),where('participantIds','array-contains',user.uid)),snap=>{const rows=snap.docs.map(d=>({id:d.id,...d.data()})).filter(x=>['pending','accepted'].includes(x.status));rows.sort((a,b)=>(b.updatedAt?.seconds||0)-(a.updatedAt?.seconds||0));setOffers(rows)},e=>console.log('Offers:',e.message))},[user]);
 if(!user||!offers.length)return null;
 const act=async(o,action)=>{try{await respondToOffer({offerId:o.id,userId:user.uid,action});if(action==='accept')Alert.alert('Offer accepted',o.buyerId===user.uid?'You can now continue to your order.':'The buyer can now continue to their order.')}catch(e){Alert.alert('Offer',e.message)}};
 const sendCounter=async()=>{try{await respondToOffer({offerId:counter.id,userId:user.uid,action:'counter',counterAmountPounds:amount});setCounter(null);setAmount('')}catch(e){Alert.alert('Counter offer',e.message)}};
 const continueOrder=async o=>{try{await createOrder({listing:{id:o.listingId,title:o.listingTitle,img:o.listingImage,sellerId:o.sellerId,price:o.amount/100},buyer:user,offer:o});onOrderCreated?.();Alert.alert('Order ready','Your accepted offer is now in Orders.')}catch(e){Alert.alert('Order',e.message)}};
 return <View style={s.wrap}><Text style={s.heading}>Offers</Text>{offers.slice(0,5).map(o=>{const mine=o.buyerId===user.uid,awaiting=(o.awaitingUserId||o.sellerId)===user.uid;const meta=(o.status==='accepted'?'Accepted':awaiting?'Your response needed':'Waiting for response')+(o.counterCount?' · '+o.counterCount+' counter'+(o.counterCount===1?'':'s'):'');return <View key={o.id} style={s.card}>{o.listingImage?<Image source={{uri:o.listingImage}} style={s.image}/>:null}<View style={{flex:1}}><Text numberOfLines={1} style={s.title}>{o.listingTitle}</Text><Text style={s.price}>£{(o.amount/100).toFixed(2)}</Text><Text style={s.meta}>{meta}</Text></View><View style={s.actions}>{o.status==='accepted'&&mine?<TouchableOpacity style={s.accept} onPress={()=>continueOrder(o)}><Text style={s.acceptText}>Continue</Text></TouchableOpacity>:o.status==='pending'&&awaiting?<><TouchableOpacity style={s.accept} onPress={()=>act(o,'accept')}><Text style={s.acceptText}>Accept</Text></TouchableOpacity><TouchableOpacity style={s.counter} onPress={()=>{setCounter(o);setAmount((o.amount/100).toFixed(2))}}><Text style={s.counterText}>Counter</Text></TouchableOpacity><TouchableOpacity onPress={()=>act(o,'decline')}><Text style={s.decline}>Decline</Text></TouchableOpacity></>:mine&&o.status==='pending'?<TouchableOpacity onPress={()=>act(o,'withdraw')}><Text style={s.decline}>Withdraw</Text></TouchableOpacity>:null}</View></View>})}<Modal visible={!!counter} transparent animationType="fade" onRequestClose={()=>setCounter(null)}><View style={s.overlay}><View style={s.sheet}><Text style={s.heading}>Counter offer</Text><Text style={s.meta}>Enter your new price. The other person will be asked to respond.</Text><TextInput value={amount} onChangeText={setAmount} keyboardType="decimal-pad" placeholder="£0.00" style={s.input}/><TouchableOpacity style={s.accept} onPress={sendCounter}><Text style={s.acceptText}>Send counter</Text></TouchableOpacity><TouchableOpacity style={s.cancel} onPress={()=>setCounter(null)}><Text>Cancel</Text></TouchableOpacity></View></View></Modal></View>
}
const s=StyleSheet.create({wrap:{paddingHorizontal:14,paddingTop:10},heading:{fontSize:18,fontWeight:'900'},card:{marginTop:10,borderWidth:1,borderColor:'#EAECF0',borderRadius:16,padding:12,flexDirection:'row',alignItems:'center',gap:10},image:{width:52,height:52,borderRadius:10,backgroundColor:'#F2F4F7'},title:{fontWeight:'900'},price:{fontWeight:'900',fontSize:17,marginTop:3},meta:{color:'#667085',fontSize:12,marginTop:3},actions:{alignItems:'flex-end',gap:6},accept:{backgroundColor:'#0A8F5A',borderRadius:12,paddingHorizontal:14,paddingVertical:9,alignItems:'center'},acceptText:{color:'#fff',fontWeight:'900'},counter:{borderWidth:1,borderColor:'#0A8F5A',borderRadius:12,paddingHorizontal:12,paddingVertical:7},counterText:{color:'#087A4D',fontWeight:'800'},decline:{color:'#B42318',fontWeight:'800',padding:4},overlay:{flex:1,backgroundColor:'rgba(0,0,0,.35)',justifyContent:'center',padding:22},sheet:{backgroundColor:'#fff',borderRadius:20,padding:20,gap:12},input:{borderWidth:1,borderColor:'#D0D5DD',borderRadius:14,paddingHorizontal:14,height:50},cancel:{height:42,alignItems:'center',justifyContent:'center'}});
