import React,{useEffect,useState}from'react';
import{View,Text,StyleSheet,FlatList,Image,TouchableOpacity,Alert,TextInput,Modal}from'react-native';
import{Ionicons}from'@expo/vector-icons';
import{collection,onSnapshot,query,where}from'firebase/firestore';
import{db}from'./firebase';
import{reportProblem}from'./commerce';

const label=s=>String(s||'pending').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const steps=['paid','ready_to_ship','shipped','delivered','completed'];

export default function OrdersScreen({user}){
 const[orders,setOrders]=useState([]),[selected,setSelected]=useState(null),[reason,setReason]=useState('Item not as expected'),[details,setDetails]=useState('');
 useEffect(()=>{if(!user){setOrders([]);return}return onSnapshot(query(collection(db,'orders'),where('participantIds','array-contains',user.uid)),snap=>{const rows=snap.docs.map(d=>({id:d.id,...d.data()}));rows.sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));setOrders(rows)},e=>console.log('Orders:',e.message))},[user]);
 if(!user)return <View style={s.empty}><Ionicons name="cube-outline" size={70} color="#15A66A"/><Text style={s.title}>Orders</Text><Text style={s.muted}>Sign in to see purchases, sales, shipping and delivery.</Text></View>;
 if(!orders.length)return <View style={s.empty}><Ionicons name="cube-outline" size={70} color="#15A66A"/><Text style={s.title}>Orders</Text><Text style={s.muted}>Your purchases and sales will appear here.</Text></View>;
 const submit=async()=>{try{await reportProblem({orderId:selected.id,userId:user.uid,reason,details});setSelected(null);setDetails('');Alert.alert('Problem reported','We have frozen the normal completion flow while this is reviewed.')}catch(e){Alert.alert('Report problem',e.message)}};
 return <View style={s.page}><FlatList data={orders} keyExtractor={x=>x.id} contentContainerStyle={{padding:14,paddingBottom:100}} renderItem={({item})=>{const seller=item.sellerId===user.uid;const current=Math.max(0,steps.indexOf(item.status));return <View style={s.card}><View style={s.row}>{item.listingImage?<Image source={{uri:item.listingImage}} style={s.image}/>:<View style={s.placeholder}><Ionicons name="image-outline" size={25} color="#667085"/></View>}<View style={{flex:1}}><Text numberOfLines={1} style={s.itemTitle}>{item.listingTitle||'WhatBuy order'}</Text><Text style={s.price}>{item.amount!=null?'£'+(item.amount/100).toFixed(2):'Price pending'}</Text><Text style={s.role}>{seller?'You sold this':'You bought this'}</Text></View></View><View style={s.status}><Text style={s.statusText}>{label(item.status)}</Text></View><View style={s.track}>{steps.map((x,i)=><View key={x} style={[s.dot,i<=current&&s.dotOn]}/>)}</View>{item.trackingNumber?<Text style={s.muted}>Tracking: {item.trackingNumber}</Text>:null}{item.shippingLabelUrl&&seller?<Text style={s.link}>Shipping label ready</Text>:null}{!['completed','refunded','cancelled','problem_reported'].includes(item.status)&&<TouchableOpacity onPress={()=>setSelected(item)} style={s.problem}><Text style={s.problemText}>Report a problem</Text></TouchableOpacity>}</View>}}/><Modal visible={!!selected} transparent animationType="fade" onRequestClose={()=>setSelected(null)}><View style={s.overlay}><View style={s.sheet}><Text style={s.title}>Report a problem</Text><Text style={s.muted}>Tell us what happened. Reporting a problem pauses the normal completion flow for review.</Text><TextInput value={reason} onChangeText={setReason} style={s.input} placeholder="Reason"/><TextInput value={details} onChangeText={setDetails} style={[s.input,s.notes]} multiline placeholder="Describe the problem"/><TouchableOpacity style={s.primary} onPress={submit}><Text style={s.primaryText}>Submit report</Text></TouchableOpacity><TouchableOpacity style={s.cancel} onPress={()=>setSelected(null)}><Text>Cancel</Text></TouchableOpacity></View></View></Modal></View>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#fff'},empty:{flex:1,alignItems:'center',justifyContent:'center',padding:40,paddingBottom:100},title:{fontSize:24,fontWeight:'900',color:'#111827'},muted:{color:'#667085',lineHeight:20,marginTop:5},card:{borderWidth:1,borderColor:'#EAECF0',borderRadius:18,padding:14,marginBottom:12},row:{flexDirection:'row',gap:12},image:{width:72,height:72,borderRadius:14},placeholder:{width:72,height:72,borderRadius:14,backgroundColor:'#F2F4F7',alignItems:'center',justifyContent:'center'},itemTitle:{fontSize:16,fontWeight:'900'},price:{fontSize:17,fontWeight:'900',marginTop:4},role:{fontSize:12,color:'#667085',marginTop:4},status:{alignSelf:'flex-start',backgroundColor:'#EAF9F2',paddingHorizontal:10,paddingVertical:6,borderRadius:14,marginTop:12},statusText:{color:'#087A4D',fontWeight:'800',fontSize:12},track:{flexDirection:'row',gap:5,marginVertical:12},dot:{height:5,flex:1,borderRadius:3,backgroundColor:'#EAECF0'},dotOn:{backgroundColor:'#0A8F5A'},link:{color:'#087A4D',fontWeight:'800',marginTop:8},problem:{marginTop:12,paddingTop:12,borderTopWidth:1,borderTopColor:'#EAECF0'},problemText:{color:'#B42318',fontWeight:'800'},overlay:{flex:1,backgroundColor:'rgba(0,0,0,.35)',justifyContent:'center',padding:22},sheet:{backgroundColor:'#fff',borderRadius:20,padding:20,gap:12},input:{borderWidth:1,borderColor:'#D0D5DD',borderRadius:14,paddingHorizontal:14,minHeight:48},notes:{height:110,textAlignVertical:'top',paddingTop:12},primary:{height:50,borderRadius:14,backgroundColor:'#0A8F5A',alignItems:'center',justifyContent:'center'},primaryText:{color:'#fff',fontWeight:'900'},cancel:{height:44,alignItems:'center',justifyContent:'center'}});