import React,{useEffect,useState}from'react';
import{View,Text,StyleSheet,TouchableOpacity,ScrollView,Alert}from'react-native';
import{Ionicons}from'@expo/vector-icons';
import{signOut}from'firebase/auth';
import{auth,db}from'./firebase';
import{collection,onSnapshot,query,where}from'firebase/firestore';
const Row=({icon,title,sub,onPress})=><TouchableOpacity style={s.row} onPress={onPress}><View style={s.icon}><Ionicons name={icon} size={21} color="#087A4D"/></View><View style={{flex:1}}><Text style={s.rowTitle}>{title}</Text>{sub?<Text style={s.sub}>{sub}</Text>:null}</View><Ionicons name="chevron-forward" size={20} color="#98A2B3"/></TouchableOpacity>;
export default function ProfileScreen({user,onNavigate}){
 const[listings,setListings]=useState([]),[savedCount,setSavedCount]=useState(0);useEffect(()=>{if(!user)return;const a=onSnapshot(query(collection(db,'listings'),where('sellerId','==',user.uid)),x=>setListings(x.docs.map(d=>({id:d.id,...d.data()}))),()=>{});const b=onSnapshot(collection(db,'users',user.uid,'favourites'),x=>setSavedCount(x.size),()=>{});return()=>{a();b()}},[user]);const name=user?.displayName||user?.email?.split('@')[0]||'WhatBuy member'; const initial=name.slice(0,1).toUpperCase();
 return <ScrollView style={s.page} contentContainerStyle={{paddingBottom:100}}><View style={s.hero}><View style={s.avatar}><Text style={s.initial}>{initial}</Text></View><Text style={s.name}>{name}</Text><Text style={s.email}>{user?.email}</Text><View style={s.verified}><Ionicons name="shield-checkmark" size={15} color="#087A4D"/><Text style={s.verifiedText}>Account signed in</Text></View></View><View style={s.stats}><TouchableOpacity style={s.stat} onPress={()=>onNavigate?.('Orders')}><Text style={s.statN}>Orders</Text><Text style={s.statL}>Purchases & sales</Text></TouchableOpacity><View style={s.div}/><View style={s.stat}><Text style={s.statN}>{listings.length}</Text><Text style={s.statL}>Listings</Text></View></View><Text style={s.section}>Your WhatBuy</Text><View style={s.group}><Row icon="pricetags-outline" title="My listings" sub={listings.length+' active listing'+(listings.length===1?'':'s')} onPress={()=>listings.length?Alert.alert('My listings',listings.map(x=>x.title).join('\n')):Alert.alert('No listings yet','Use Sell to publish your first item.')}/><Row icon="heart-outline" title="Saved items" sub={savedCount+' saved item'+(savedCount===1?'':'s')}/></View><Text style={s.section}>Support & safety</Text><View style={s.group}><Row icon="shield-checkmark-outline" title="Order protection" sub="Open an order to track it or report a problem" onPress={()=>onNavigate?.('Orders')}/></View><TouchableOpacity style={s.signout} onPress={()=>signOut(auth)}><Ionicons name="log-out-outline" size={20} color="#B42318"/><Text style={s.signoutText}>Sign out</Text></TouchableOpacity></ScrollView>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F8FAF9'},hero:{backgroundColor:'#fff',alignItems:'center',padding:24,borderBottomWidth:1,borderColor:'#EAECF0'},avatar:{width:76,height:76,borderRadius:38,backgroundColor:'#DDF7EC',alignItems:'center',justifyContent:'center'},initial:{fontSize:30,fontWeight:'900',color:'#087A4D'},name:{fontSize:22,fontWeight:'900',marginTop:12,textTransform:'capitalize'},email:{color:'#667085',marginTop:3},verified:{flexDirection:'row',gap:5,alignItems:'center',marginTop:10,backgroundColor:'#EAF9F2',paddingHorizontal:10,paddingVertical:5,borderRadius:14},verifiedText:{fontSize:12,color:'#087A4D',fontWeight:'800'},stats:{backgroundColor:'#fff',marginTop:10,padding:16,flexDirection:'row'},stat:{flex:1,alignItems:'center'},statN:{fontWeight:'900'},statL:{fontSize:12,color:'#667085',marginTop:3},div:{width:1,backgroundColor:'#EAECF0'},section:{fontSize:13,fontWeight:'900',color:'#667085',paddingHorizontal:16,paddingTop:22,paddingBottom:8,textTransform:'uppercase'},group:{backgroundColor:'#fff',borderTopWidth:1,borderBottomWidth:1,borderColor:'#EAECF0'},row:{minHeight:68,flexDirection:'row',alignItems:'center',gap:12,paddingHorizontal:16,borderBottomWidth:1,borderBottomColor:'#F2F4F7'},icon:{width:40,height:40,borderRadius:12,backgroundColor:'#EAF9F2',alignItems:'center',justifyContent:'center'},rowTitle:{fontWeight:'850',fontSize:15},sub:{color:'#667085',fontSize:12,marginTop:2},signout:{margin:16,marginTop:24,height:52,borderRadius:14,borderWidth:1,borderColor:'#FDA29B',flexDirection:'row',gap:8,alignItems:'center',justifyContent:'center',backgroundColor:'#fff'},signoutText:{color:'#B42318',fontWeight:'900'}});