// ChannelDesk sequential Agnes video worker: one active generation per workspace; Standard uses Video 2.5 Flash.
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';import {json,service} from '../_shared/core.ts';
const BASE='https://apihub.agnes-ai.com',MAX=256*1024*1024;
function doneUrl(b:any){return [b?.metadata?.url,b?.url,b?.data?.url,b?.video_url,b?.data?.video_url].find((x:any)=>typeof x==='string'&&x.startsWith('https://')) as string|undefined}
async function agnes(key:string,path:string,init:RequestInit={}){const r=await fetch(BASE+path,{...init,headers:{Authorization:'Bearer '+key,'Content-Type':'application/json',...(init.headers||{})},signal:AbortSignal.timeout(45000)});const text=await r.text();let body:any={};try{body=text?JSON.parse(text):{}}catch{}if(!r.ok)throw new Error(String(body?.error?.message||body?.message||text||('Agnes HTTP '+r.status)).slice(0,1000));return body}
async function startNext(db:any,key:string,workspaceId:string){const {data:active}=await db.from('platform_jobs').select('id').eq('workspace_id',workspaceId).eq('kind','ai.video').eq('provider','agnes').eq('status','processing').limit(1);if(active?.length)return null;
 const {data:next}=await db.from('platform_jobs').select('*').eq('workspace_id',workspaceId).eq('kind','ai.video').eq('provider','agnes').in('status',['queued','retry']).lte('available_at',new Date().toISOString()).order('created_at',{ascending:true}).limit(1).maybeSingle();if(!next)return null;
 const legacyId=next.payload?.legacyJobId,concept=next.payload?.concept||{},quality=next.payload?.quality==='quality'?'quality':'flash',model=String(next.payload?.model||(quality==='quality'?'agnes-video-2.5':'agnes-video-2.5-flash')),size=String(next.payload?.size||(quality==='quality'?'1080P':'720P')),seconds=Math.max(4,Math.min(12,Math.round(Number(next.payload?.seconds||concept.seconds)||8))),ratio=String(next.payload?.ratio||concept.aspectRatio||'9:16'),prompt=String(concept.videoPrompt||'').trim();
 await db.from('platform_jobs').update({status:'processing',locked_at:new Date().toISOString(),locked_by:'job-worker',attempts:Number(next.attempts||0)+1,updated_at:new Date().toISOString()}).eq('id',next.id).in('status',['queued','retry']);
 try{const out=await agnes(key,'/v1/videos',{method:'POST',body:JSON.stringify({model,prompt,mode:'text',seconds:String(seconds),size,aspect_ratio:ratio})});const external=String(out?.video_id||out?.id||out?.data?.video_id||'');if(!external)throw new Error('Agnes returned no video job ID');await db.from('platform_jobs').update({external_job_id:external,result:{providerAccepted:true,legacyJobId:legacyId,progress:0},updated_at:new Date().toISOString(),last_error:null}).eq('id',next.id);if(legacyId)await db.from('ai_generation_jobs').update({status:'generating',provider_job_id:external,result:{progress:0,platformJobId:next.id,quality,size},updated_at:new Date().toISOString(),error_message:null}).eq('id',legacyId);return {id:next.id,status:'processing',legacyJobId:legacyId}}
 catch(e){const msg=e instanceof Error?e.message:'generation start failed',attempts=Number(next.attempts||0)+1,hard=/free users|token plan|upgrade|quota|credits?/i.test(msg),failed=hard||attempts>=Number(next.max_attempts||5);await db.from('platform_jobs').update({status:failed?'failed':'retry',last_error:msg,available_at:new Date(Date.now()+Math.min(3600000,30000*2**Math.min(attempts,6))).toISOString(),updated_at:new Date().toISOString(),locked_at:null,locked_by:null}).eq('id',next.id);if(legacyId)await db.from('ai_generation_jobs').update({status:failed?'failed':'queued',error_message:failed?msg:null,result:{progress:0,failure_class:hard?'quota_exhausted':'rate_limited'},updated_at:new Date().toISOString()}).eq('id',legacyId);return {id:next.id,status:failed?'failed':'retry',error:msg}}
}
Deno.serve(async(req:Request)=>{if(req.method!=='POST')return json({error:'Method not allowed'},405);const secret=Deno.env.get('WORKER_SECRET'),serviceKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'),bearer=req.headers.get('authorization')?.replace(/^Bearer\s+/i,'');if(!((secret&&req.headers.get('x-worker-secret')===secret)||(serviceKey&&bearer===serviceKey)))return json({error:'Unauthorized'},401);const db=service(),key=Deno.env.get('AGNES_API_KEY');if(!key)return json({error:'AGNES_API_KEY missing'},500);const results:any[]=[];
 const {data:jobs,error}=await db.from('platform_jobs').select('*').eq('kind','ai.video').eq('provider','agnes').eq('status','processing').not('external_job_id','is',null).order('updated_at').limit(25);if(error)return json({error:error.message},500);
 for(const job of jobs||[]){try{const model=String(job.payload?.model||(job.payload?.quality==='quality'?'agnes-video-2.5':'agnes-video-2.5-flash')),body=await agnes(key,'/agnesapi?video_id='+encodeURIComponent(job.external_job_id)+'&model_name='+encodeURIComponent(model)),url=doneUrl(body),state=String(body?.status||body?.state||body?.metadata?.status||'').toLowerCase(),legacyId=job.payload?.legacyJobId,progress=Math.max(0,Math.min(100,Math.round(Number(body?.progress??body?.metadata?.progress??0)||0)));
  if(url){const media=await fetch(url,{redirect:'follow',signal:AbortSignal.timeout(120000)});if(!media.ok)throw new Error('Generated video download failed (HTTP '+media.status+').');const len=Number(media.headers.get('content-length')||0);if(len>MAX)throw new Error('Generated video exceeds 256 MB.');const bytes=await media.arrayBuffer();if(bytes.byteLength>MAX)throw new Error('Generated video exceeds 256 MB.');const assetId=crypto.randomUUID(),storageKey=job.workspace_id+'/'+assetId+'/agnes-'+job.id+'.mp4';const up=await db.storage.from('channeldesk-media').upload(storageKey,bytes,{contentType:'video/mp4',upsert:false,cacheControl:'3600'});if(up.error)throw up.error;const {error:ae}=await db.from('media_assets').insert({id:assetId,workspace_id:job.workspace_id,storage_key:storageKey,mime_type:'video/mp4',source_url:'ai://agnes/'+job.external_job_id,rights_basis:'ai_generated',rights_evidence:'Agnes '+model+'; job '+job.external_job_id});if(ae){await db.storage.from('channeldesk-media').remove([storageKey]);throw ae}if(legacyId)await db.from('ai_generation_jobs').update({status:'completed',media_asset_id:assetId,result:{provider:body,progress:100},error_message:null,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',legacyId);await db.from('platform_jobs').update({status:'completed',result:{provider:body,mediaAssetId:assetId,progress:100},completed_at:new Date().toISOString(),updated_at:new Date().toISOString(),last_error:null,locked_at:null,locked_by:null}).eq('id',job.id);await db.from('audit_events').insert({workspace_id:job.workspace_id,actor_id:job.created_by,action:'ai.video_generated',entity_type:'media_asset',entity_id:assetId,metadata:{provider:'agnes',platform_job_id:job.id,provider_job_id:job.external_job_id}});results.push({id:job.id,status:'completed',mediaAssetId:assetId,progress:100});
  }else if(['failed','error','cancelled','rejected'].includes(state)){const msg='Agnes generation failed: '+state;if(legacyId)await db.from('ai_generation_jobs').update({status:'failed',error_message:msg,result:{provider:body,progress},updated_at:new Date().toISOString()}).eq('id',legacyId);await db.from('platform_jobs').update({status:'failed',result:{provider:body,progress},last_error:msg,updated_at:new Date().toISOString(),locked_at:null,locked_by:null}).eq('id',job.id);results.push({id:job.id,status:'failed',progress});
  }else{if(legacyId)await db.from('ai_generation_jobs').update({status:'generating',result:{provider:body,progress},updated_at:new Date().toISOString()}).eq('id',legacyId);await db.from('platform_jobs').update({result:{provider:body,progress},updated_at:new Date().toISOString()}).eq('id',job.id);results.push({id:job.id,status:'processing',progress});}
 }catch(e){const msg=e instanceof Error?e.message:'sync failed',attempts=Number(job.attempts||0)+1,failed=attempts>=Number(job.max_attempts||5);await db.from('platform_jobs').update({attempts,status:failed?'failed':'processing',last_error:msg,available_at:new Date(Date.now()+Math.min(3600000,30000*2**Math.min(attempts,6))).toISOString(),updated_at:new Date().toISOString()}).eq('id',job.id);results.push({id:job.id,status:failed?'failed':'processing',error:msg});}}
 const {data:workspaces}=await db.from('platform_jobs').select('workspace_id').eq('kind','ai.video').eq('provider','agnes').in('status',['queued','retry']);for(const workspaceId of [...new Set((workspaces||[]).map((x:any)=>x.workspace_id))]){const started=await startNext(db,key,String(workspaceId));if(started)results.push(started)}
 return json({processed:results.length,results});});
