"use client";
import {useState} from 'react';
import Link from 'next/link';
import {Upload,CheckCircle2} from 'lucide-react';
import {parseDraftCsv} from '@/lib/draft-import';
type Row={id:string;caption:string;row:number};
export function DraftImport({workspaceId}:{workspaceId:string}){
 const [rows,setRows]=useState<Row[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState<number|null>(null);
 async function fileSelected(file:File|undefined){if(!file)return;setRows([]);setError('');setDone(null);try{if(file.size>256*1024)throw new Error('Choose a CSV file smaller than 256 KB.');setRows(parseDraftCsv(await file.text()).map(r=>({...r,id:crypto.randomUUID()})))}catch(e){setError(e instanceof Error?e.message:'This file could not be read.')}}
 async function save(){if(busy||done!==null)return;setBusy(true);setError('');try{const response=await fetch('/api/planner/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspaceId,rows:rows.map(({id,caption})=>({id,caption}))})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Import failed.');setDone(data.count)}catch(e){setError(e instanceof Error?e.message:'Connection interrupted. Retry with this same preview to avoid duplicates.')}finally{setBusy(false)}}
 return <><div className="page-title"><div><p className="eyebrow">BULK DRAFTS</p><h1>Turn your content list into a plan.</h1><p className="muted">Import up to 100 captions. Nothing is scheduled or published.</p></div><Link className="button secondary-button" href="/planner">Back to calendar</Link></div><section className="panel"><h2>1. Choose your CSV</h2><p className="muted">Use one column named <code>caption</code>. Quote captions that contain commas or line breaks. Remove date or scheduling columns.</p><a className="cd-csv-template" href={'data:text/csv;charset=utf-8,'+encodeURIComponent('caption\r\n"Introduce your next idea"\r\n"A helpful tip for your audience"\r\n')} download="channeldesk-draft-template.csv">Download a CSV template</a><label className="cd-import-file"><Upload/><span>Choose a CSV file · maximum 256 KB</span><input type="file" accept=".csv,text/csv" disabled={busy} onChange={e=>void fileSelected(e.target.files?.[0])}/></label></section>{error&&<p className="notice error" role="alert">{error}</p>}{done!==null?<section className="panel cd-quiet-empty" role="status"><CheckCircle2/><h2>{done} drafts saved</h2><p>Open a draft in Planner and use its caption to create a post. Choose accounts and media before publishing.</p><Link href="/planner?status=draft" className="button">View your drafts</Link></section>:rows.length>0?<section className="panel"><h2>2. Review {rows.length} captions</h2><p className="muted">These are caption-only drafts. Accounts, media and delivery times are chosen later.</p><ol className="cd-import-preview">{rows.map(r=><li key={r.id}><small>CSV row {r.row} · {r.caption.length}/2,200 characters</small><p>{r.caption}</p></li>)}</ol><button disabled={busy} onClick={()=>void save()}>{busy?'Saving drafts…':`Save ${rows.length} unscheduled drafts`}</button></section>:null}</>;
}
