'use client';import {useEffect,useRef,useState,useTransition} from 'react';import Link from 'next/link';import {Check,Film,LoaderCircle,Sparkles,WandSparkles} from 'lucide-react';import {generateAiVideo,planAiContent,refreshAiVideo} from './ai-actions';import type {AiConcept} from '@/lib/agnes';
export function AiStudio(){const [brief,setBrief]=useState(''),[platform,setPlatform]=useState('tiktok'),[concept,setConcept]=useState<AiConcept|null>(null),[job,setJob]=useState<{id:string;status:string;mediaAssetId?:string|null;progress?:unknown}|null>(null),[error,setError]=useState(''),[quality,setQuality]=useState<'flash'|'quality'>('flash'),[busy,start]=useTransition(),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
 const plan=()=>{setError('');start(async()=>{try{const r=await planAiContent(brief,platform);if(!r.ok){setError(r.error);return}setConcept(r.data);setJob(null)}catch(e){setError(e instanceof Error?e.message:'Could not create a content plan.')}})};
 const generate=()=>{if(!concept)return;setError('');start(async()=>{try{const r=await generateAiVideo(concept,quality);if(!r.ok){setError(r.error);return}const next=r.data;setJob(next);poll(next.id)}catch(e){setError(e instanceof Error?e.message:'Could not start video generation.')}})};
 const poll=(id:string)=>{if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(async()=>{try{const r=await refreshAiVideo(id);if(!r.ok){setError(r.error);return}const next=r.data;setJob(next);if(next.status==='generating'||next.status==='queued')poll(id);else if(next.status==='failed')setError(next.error||'Video generation failed.')}catch(e){setError(e instanceof Error?e.message:'Could not check video status.');poll(id)}},8000)};
 return <section className="ai-studio"><div className="ai-studio-intro"><span><Sparkles/></span><div><b>Create with AI</b><p>Describe the outcome. ChannelDesk plans the creative, writes the copy and generates a ready-to-use social video.</p></div><span className="beta">Agnes AI</span></div><div className="ai-studio-body"><label className="ai-brief">What do you want to create?<textarea value={brief} onChange={e=>setBrief(e.target.value)} maxLength={3000} placeholder="e.g. Create a punchy TikTok introducing our bookkeeping service to new limited companies. Professional, friendly and no exaggerated claims."/></label><div className="ai-options"><label>Target channel<select value={platform} onChange={e=>setPlatform(e.target.value)}><option value="tiktok">TikTok</option><option value="instagram">Instagram / Reels</option><option value="youtube">YouTube / Shorts</option><option value="facebook">Facebook</option><option value="linkedin">LinkedIn</option><option value="x">X</option><option value="general">General social</option></select></label><button type="button" onClick={plan} disabled={busy||brief.trim().length<8}><WandSparkles/>{busy&&!concept?'Planning…':'Build my content'}</button></div>{error?<p className="notice error" role="alert">{error}</p>:null}
 {concept?<div className="ai-concept"><div className="ai-concept-head"><div><small>AI CREATIVE PLAN</small><h3>{concept.title||'Your social video'}</h3></div><span>{concept.aspectRatio} · {concept.seconds}s</span></div><div className="ai-concept-grid"><div><small>Hook</small><p>{concept.hook}</p></div><div><small>Call to action</small><p>{concept.cta}</p></div><div className="wide"><small>Script</small><p>{concept.script}</p></div><div className="wide"><small>Caption</small><p>{concept.caption}</p><div className="ai-tags">{concept.hashtags.map(x=><span key={x}>#{x}</span>)}</div></div></div><details><summary>Video generation prompt</summary><p>{concept.videoPrompt}</p></details><div className="ai-generate-row"><label>Generation quality<select value={quality} onChange={e=>setQuality(e.target.value as 'flash'|'quality')} disabled={!!job&&job.status==='generating'}><option value="flash">Standard · 720P</option><option value="quality">Quality · 1080P</option></select></label><button type="button" onClick={generate} disabled={busy||job?.status==='generating'}><Film/>{job?.status==='generating'?'Generating…':'Generate video'}</button></div></div>:null}
 {job?<div className={"ai-job "+job.status}>{job.status==='completed'?<Check/>:<LoaderCircle className={job.status==='generating'?'spin':''}/>}<div><b>{job.status==='completed'?'Video ready':job.status==='failed'?'Generation failed':'Creating your video'}</b><span>{job.status==='completed'?'Saved privately to your ChannelDesk Media Library.':job.status==='generating'?'You can stay here while ChannelDesk checks Agnes automatically.':'Please review the error above.'}</span></div>{job.status==='completed'?<><Link className="button secondary" href="/media">View media</Link><Link className="button" href={"/create?media="+encodeURIComponent(job.mediaAssetId||'')}>Use in post</Link></>:null}</div>:null}</div></section>}
