'use client';
import {useMemo,useState,useTransition} from 'react';
import Link from 'next/link';
import {SocialIcon} from '@/components/social-icon';
import {publishWizard,type WizardOutcome} from './wizard-actions';

type Account={id:string;network:string;display_name:string;workspace_id:string;scopes?:string[]};
type Asset={id:string;workspace_id:string;mime_type:string;source_url:string|null;storage_key:string;duration_ms:number|null};
const networks=['facebook','instagram','tiktok','youtube'];
const steps=['Accounts','Media','Caption & settings','Review & publish'];
export function CreateWizard({accounts,assets,initialDate,initialMediaId}:{accounts:Account[];assets:Asset[];initialDate?:string;initialMediaId?:string}){
 const [step,setStep]=useState(0),[selected,setSelected]=useState<string[]>([]),[mediaId,setMediaId]=useState(initialMediaId||''),[caption,setCaption]=useState(''),[title,setTitle]=useState(''),[privacy,setPrivacy]=useState<'public'|'private'|'unlisted'>('public'),[tiktokPrivacy,setTiktokPrivacy]=useState<'PUBLIC_TO_EVERYONE'|'MUTUAL_FOLLOW_FRIENDS'|'SELF_ONLY'>('SELF_ONLY'),[madeForKids,setMadeForKids]=useState(false),[schedule,setSchedule]=useState(!!initialDate),[date,setDate]=useState(initialDate?initialDate+'T12:00':''),[result,setResult]=useState<WizardOutcome[]|null>(null),[error,setError]=useState(''),[pending,start]=useTransition();
 const chosen=accounts.filter(a=>selected.includes(a.id)),media=assets.find(a=>a.id===mediaId);
 const needVideo=chosen.some(a=>['youtube','tiktok'].includes(a.network));
 const needMedia=chosen.some(a=>['youtube','tiktok','instagram'].includes(a.network));
 const incompatible=needVideo&&!media?.mime_type.startsWith('video/');
 const invalidSchedule=schedule&&(!date||chosen.some(a=>a.network==='instagram'));
 const canProceed=step===0?chosen.length>0:step===1?(!needMedia||!!media)&&!incompatible:step===2?!!caption.trim()&&(!chosen.some(a=>a.network==='youtube')||!!title.trim())&&!invalidSchedule:true;
 const workspace=chosen[0]?.workspace_id||accounts[0]?.workspace_id;
 const visibleAssets=assets.filter(a=>a.workspace_id===workspace);
 const grouped=useMemo(()=>networks.map(network=>({network,items:accounts.filter(a=>a.network===network)})).filter(g=>g.items.length),[accounts]);
 const toggle=(id:string)=>{const candidate=accounts.find(a=>a.id===id);if(!candidate)return;setSelected(old=>old.includes(id)?old.filter(x=>x!==id):old.some(x=>accounts.find(a=>a.id===x)?.workspace_id!==candidate.workspace_id)?[id]:[...old,id]);setResult(null);};
 const go=(next:number)=>{setError('');setStep(next);};
 const submit=()=>start(async()=>{setError('');setResult(null);try{const results=await publishWizard({accountIds:selected,mediaId:mediaId||null,caption,title,privacy,madeForKids,tiktokPrivacy,scheduledFor:schedule?new Date(date).toISOString():null});setResult(results);}catch(e){setError(e instanceof Error?e.message:'Unable to publish.');}});
 return <div className="panel create-panel" style={{maxWidth:1000,margin:'0 auto'}}>
  <div className="wizard-steps" aria-label="Create post steps" style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:24}}>{steps.map((label,i)=><button key={label} type="button" className={i===step?'button':'secondary-button'} disabled={pending||i>step} onClick={()=>go(i)} style={{fontSize:12}}>{i+1}. {label}</button>)}</div>
  {step===0&&<section><h2>Where should this post go?</h2><p className="muted">Select one or multiple accounts. Only accounts you tick will receive the post.</p>{grouped.map(group=><div key={group.network} style={{margin:'18px 0'}}><div className="channel-heading"><span className={'network-mark '+group.network}><SocialIcon network={group.network}/></span><b>{group.network[0].toUpperCase()+group.network.slice(1)}</b></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:10,marginTop:8}}>{group.items.map(account=><label key={account.id} className="panel" style={{padding:12,cursor:'pointer',display:'flex',gap:12,alignItems:'center'}}><input type="checkbox" checked={selected.includes(account.id)} onChange={()=>toggle(account.id)}/><span>{account.display_name}</span></label>)}</div></div>)}</section>}
  {step===1&&<section><h2>Choose your creative</h2><p className="muted">Pick existing media. Image posts work on Facebook and Instagram; TikTok and YouTube require a video.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(180px,1fr))',gap:12}}>{visibleAssets.map(asset=><label key={asset.id} className="panel" style={{padding:12,cursor:'pointer',outline:mediaId===asset.id?'2px solid currentColor':undefined}}><input type="radio" name="wizardMedia" checked={mediaId===asset.id} onChange={()=>setMediaId(asset.id)}/><span style={{display:'block',margin:'8px 0'}}>{asset.mime_type.startsWith('video/')?<video src={'/media/'+asset.id} style={{width:'100%',maxHeight:160}} muted preload="metadata" controls/>:<img src={'/media/'+asset.id} alt="Media preview" style={{width:'100%',maxHeight:160,objectFit:'contain'}}/>}</span><small>{asset.storage_key.split('/').pop()} · {asset.mime_type.startsWith('video/')?'Video':'Image'}{asset.duration_ms?' · '+Math.round(asset.duration_ms/1000)+'s':''}</small></label>)}</div>{!needMedia&&<button type="button" className="secondary-button" onClick={()=>setMediaId('')} style={{marginTop:12}}>Text-only post</button>}{incompatible&&<p className="notice error" role="alert">A selected TikTok or YouTube account requires MP4 video. Image-to-video conversion with sound and effects is not yet available inside this wizard. <Link href="/media">Upload a video</Link> to proceed.</p>}<p className="form-hint" style={{marginTop:15}}>Need to add media? <Link href="/media">Upload to Media Library</Link>, then come back here.</p></section>}
  {step===2&&<section><h2>Write your post</h2><p className="muted">One caption shared across selected channels. Review the accounts before publishing.</p><div className="auth-form publish-form"><label>Caption<textarea className="composer compact-composer" value={caption} maxLength={2200} onChange={e=>setCaption(e.target.value)} rows={5} placeholder="What do you want to share? Add hashtags here." /></label>{chosen.some(a=>a.network==='youtube')&&<><label>YouTube title<input maxLength={100} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Video title"/></label><label>YouTube visibility<select value={privacy} onChange={e=>setPrivacy(e.target.value as typeof privacy)}><option value="public">Public</option><option value="unlisted">Unlisted</option><option value="private">Private</option></select></label><label><input type="checkbox" checked={madeForKids} onChange={e=>setMadeForKids(e.target.checked)}/> This video is made for kids</label></>}{chosen.some(a=>a.network==='tiktok')&&<label>TikTok visibility<select value={tiktokPrivacy} onChange={e=>setTiktokPrivacy(e.target.value as typeof tiktokPrivacy)}><option value="SELF_ONLY">Only me (safest default)</option><option value="PUBLIC_TO_EVERYONE">Everyone</option><option value="MUTUAL_FOLLOW_FRIENDS">Friends</option></select></label>}<label><input type="checkbox" checked={schedule} onChange={e=>setSchedule(e.target.checked)}/> Schedule for later</label>{schedule&&<label>Date and time<input type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/></label>}{schedule&&chosen.some(a=>a.network==='instagram')&&<p className="notice error">Instagram scheduling is not currently enabled. Publish now or deselect Instagram.</p>}</div></section>}
  {step===3&&<section><h2>Review before publishing</h2><p className="muted">Only these {chosen.length} account(s) will be used. This action sends your content to live networks.</p><div className="panel" style={{padding:16}}><b>Destinations</b><p>{chosen.map(a=>a.network+': '+a.display_name).join(' · ')}</p><b>Creative</b><p>{media?.storage_key.split('/').pop()||'Text only'}</p><b>Caption</b><p style={{whiteSpace:'pre-wrap'}}>{caption}</p><b>Delivery</b><p>{schedule?('Scheduled for '+new Date(date).toLocaleString()):'Publish now'}</p></div>{!result&&<button className="publish-button" type="button" disabled={pending} onClick={submit}>{pending?'Publishing…':schedule?'Confirm schedule':'Confirm and publish'}</button>}{result&&<div aria-live="polite" style={{marginTop:18}}><h3>Results</h3>{result.map(r=><div key={r.id} className={r.status==='failed'?'notice error':'notice'} style={{marginBottom:8}}><strong>{r.network}: {r.name}</strong> — {r.status}. {r.message}</div>)}<p className="form-hint">If a destination failed or needs review, check its Planner record before retrying to avoid duplicate posts.</p></div>}</section>}
  {error&&<p className="notice error" role="alert">{error}</p>}
  <div className="publish-actions" style={{display:'flex',justifyContent:'space-between',marginTop:24}}><button type="button" className="secondary-button" disabled={step===0||pending} onClick={()=>go(step-1)}>Back</button>{step<3&&<button type="button" className="button" disabled={!canProceed||pending} onClick={()=>go(step+1)}>Continue →</button>}</div>
 </div>;
}
