'use client';
import {useState} from 'react';
import {useFormStatus} from 'react-dom';
import {submitTikTok} from './actions';
import {MediaPicker,type MediaAsset} from './media-picker';
function Submit({disabled}:{disabled:boolean}){const {pending}=useFormStatus();return <button className="publish-button" disabled={pending||disabled}>{pending?'Sending to TikTok…':'Continue with TikTok'}</button>;}
export function TikTokForm({accounts,assets,requestId}:{accounts:{id:string;display_name:string;workspace_id:string}[];assets:MediaAsset[];requestId:string}){
 const [mode,setMode]=useState('draft');
 return <form action={submitTikTok} className="auth-form publish-form"><input type="hidden" name="requestId" value={requestId}/><label>Publish to<select name="connectionId" required defaultValue={accounts.length===1?accounts[0].id:''}><option value="" disabled>Choose TikTok account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.display_name}</option>)}</select></label><MediaPicker assets={assets}/><label>Caption<textarea name="caption" className="composer compact-composer" maxLength={2200} placeholder="Write your TikTok caption"/></label><label>How do you want to publish?<select name="mode" required value={mode} onChange={e=>setMode(e.target.value)}><option value="draft">Send to TikTok drafts</option><option value="direct">Post directly</option></select></label>{mode==='direct'?<label>Who can watch?<select name="privacy" defaultValue="SELF_ONLY"><option value="SELF_ONLY">Only me</option><option value="FOLLOWER_OF_CREATOR">Followers</option><option value="MUTUAL_FOLLOW_FRIENDS">Friends</option><option value="PUBLIC_TO_EVERYONE">Everyone</option></select></label>:<p className="form-hint">You&apos;ll finish editing and publishing inside TikTok.</p>}<Submit disabled={!assets.length}/></form>;
}