'use client';
import {useState} from 'react';
import {useFormStatus} from 'react-dom';
import {submitYouTube} from './actions';
function Submit(){const {pending}=useFormStatus();return <button disabled={pending}>{pending?'Uploading video…':'Publish / schedule on YouTube'}</button>;}
export function YouTubeForm({accounts,requestId}:{accounts:{id:string;display_name:string;workspace_id:string}[];requestId:string}){
 const [date,setDate]=useState('');const [iso,setIso]=useState('');
 return <form action={submitYouTube} className="auth-form"><input type="hidden" name="requestId" value={requestId}/><label>YouTube account<select name="connectionId" required defaultValue=""><option value="" disabled>Choose the exact channel</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.display_name} · {a.workspace_id.slice(0,8)}</option>)}</select></label><label>Video title<input name="title" required maxLength={100}/></label><label>Description<textarea name="description" className="composer" maxLength={5000}/></label><label>Public HTTPS video URL<input name="mediaUrl" type="url" required placeholder="https://…/video.mp4"/></label><small>Up to 256 MB. The video server must provide the file size.</small><label>Publish time (optional, in your device’s local timezone)<input type="datetime-local" value={date} onChange={e=>{setDate(e.target.value);const value=new Date(e.target.value);setIso(Number.isFinite(value.getTime())?value.toISOString():'');}}/></label><input type="hidden" name="scheduledFor" value={iso}/>{iso&&<small>Scheduled instant: {iso}. YouTube keeps it private until then.</small>}<label>Visibility<select name="privacy" required defaultValue=""><option value="" disabled>Choose visibility</option><option value="public">Public</option><option value="unlisted">Unlisted</option><option value="private">Private</option></select></label><label>Is this video made for kids?<select name="madeForKids" required defaultValue=""><option value="" disabled>Choose an audience</option><option value="yes">Yes, made for kids</option><option value="no">No, not made for kids</option></select></label><p className="muted">Publishing starts when you submit. Google may restrict unapproved apps to private uploads.</p><Submit/></form>;
}
