'use client';
import {useState} from 'react';
import {useFormStatus} from 'react-dom';
import {saveDraft,submitYouTube} from './actions';
import {MediaPicker,type MediaAsset} from './media-picker';
function Submit({disabled}:{disabled:boolean}){const {pending}=useFormStatus();return <button className="publish-button" disabled={pending||disabled}>{pending?'Sending to YouTube…':'Publish / schedule on YouTube'}</button>;}
export function YouTubeForm({accounts,assets,requestId}:{accounts:{id:string;display_name:string;workspace_id:string}[];assets:MediaAsset[];requestId:string}){
 const [date,setDate]=useState('');const [iso,setIso]=useState('');
 return <form action={submitYouTube} className="auth-form publish-form"><input type="hidden" name="network" value="youtube"/><input type="hidden" name="requestId" value={requestId}/><label>Publish to<select name="connectionId" required defaultValue={accounts.length===1?accounts[0].id:''}><option value="" disabled>Choose YouTube channel</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.display_name}</option>)}</select></label><MediaPicker assets={assets}/><label>Video title<input name="title" required maxLength={100} placeholder="Give viewers a clear reason to watch"/></label><label>Description<textarea name="description" className="composer compact-composer" maxLength={5000} placeholder="Add context, links or a call to action"/></label><div className="form-row"><label>Visibility<select name="privacy" required defaultValue="private"><option value="private">Private</option><option value="unlisted">Unlisted</option><option value="public">Public</option></select></label><label>Audience<select name="madeForKids" required defaultValue=""><option value="" disabled>Choose audience</option><option value="no">No, not made for kids</option><option value="yes">Yes, made for kids</option></select></label></div><label>Schedule for later <span className="optional">(optional)</span><input type="datetime-local" value={date} onChange={e=>{setDate(e.target.value);const value=new Date(e.target.value);setIso(Number.isFinite(value.getTime())?value.toISOString():'');}}/></label><input type="hidden" name="scheduledFor" value={iso}/>{iso&&<small className="form-hint">Scheduled for {new Date(iso).toLocaleString()} on this device.</small>}<div className="publish-actions"><button className="secondary-button" formAction={saveDraft} disabled={!assets.length}>Save draft</button><Submit disabled={!assets.length}/></div></form>;
}